// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/agentgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayPolicies implements AgentgatewayPolicyInterface
type fakeAgentgatewayPolicies struct {
	*gentype.FakeClientWithList[*agentgateway.AgentgatewayPolicy, *agentgateway.AgentgatewayPolicyList]
	Fake *FakeGatewayAgentgateway
}

func newFakeAgentgatewayPolicies(fake *FakeGatewayAgentgateway, namespace string) v1alpha1agentgateway.AgentgatewayPolicyInterface {
	return &fakeAgentgatewayPolicies{
		gentype.NewFakeClientWithList[*agentgateway.AgentgatewayPolicy, *agentgateway.AgentgatewayPolicyList](
			fake.Fake,
			namespace,
			agentgateway.SchemeGroupVersion.WithResource("agentgatewaypolicies"),
			agentgateway.SchemeGroupVersion.WithKind("AgentgatewayPolicy"),
			func() *agentgateway.AgentgatewayPolicy { return &agentgateway.AgentgatewayPolicy{} },
			func() *agentgateway.AgentgatewayPolicyList { return &agentgateway.AgentgatewayPolicyList{} },
			func(dst, src *agentgateway.AgentgatewayPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *agentgateway.AgentgatewayPolicyList) []*agentgateway.AgentgatewayPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *agentgateway.AgentgatewayPolicyList, items []*agentgateway.AgentgatewayPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
