// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/agentgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayParameters implements AgentgatewayParametersInterface
type fakeAgentgatewayParameters struct {
	*gentype.FakeClientWithList[*agentgateway.AgentgatewayParameters, *agentgateway.AgentgatewayParametersList]
	Fake *FakeGatewayAgentgateway
}

func newFakeAgentgatewayParameters(fake *FakeGatewayAgentgateway, namespace string) v1alpha1agentgateway.AgentgatewayParametersInterface {
	return &fakeAgentgatewayParameters{
		gentype.NewFakeClientWithList[*agentgateway.AgentgatewayParameters, *agentgateway.AgentgatewayParametersList](
			fake.Fake,
			namespace,
			agentgateway.SchemeGroupVersion.WithResource("agentgatewayparameters"),
			agentgateway.SchemeGroupVersion.WithKind("AgentgatewayParameters"),
			func() *agentgateway.AgentgatewayParameters { return &agentgateway.AgentgatewayParameters{} },
			func() *agentgateway.AgentgatewayParametersList { return &agentgateway.AgentgatewayParametersList{} },
			func(dst, src *agentgateway.AgentgatewayParametersList) { dst.ListMeta = src.ListMeta },
			func(list *agentgateway.AgentgatewayParametersList) []*agentgateway.AgentgatewayParameters {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *agentgateway.AgentgatewayParametersList, items []*agentgateway.AgentgatewayParameters) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
