// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	agentgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/agentgateway"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGatewayAgentgateway struct {
	*testing.Fake
}

func (c *FakeGatewayAgentgateway) AgentgatewayBackends(namespace string) agentgateway.AgentgatewayBackendInterface {
	return newFakeAgentgatewayBackends(c, namespace)
}

func (c *FakeGatewayAgentgateway) AgentgatewayParameters(namespace string) agentgateway.AgentgatewayParametersInterface {
	return newFakeAgentgatewayParameters(c, namespace)
}

func (c *FakeGatewayAgentgateway) AgentgatewayPolicies(namespace string) agentgateway.AgentgatewayPolicyInterface {
	return newFakeAgentgatewayPolicies(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGatewayAgentgateway) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
