// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/agentgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayBackends implements AgentgatewayBackendInterface
type fakeAgentgatewayBackends struct {
	*gentype.FakeClientWithList[*agentgateway.AgentgatewayBackend, *agentgateway.AgentgatewayBackendList]
	Fake *FakeGatewayAgentgateway
}

func newFakeAgentgatewayBackends(fake *FakeGatewayAgentgateway, namespace string) v1alpha1agentgateway.AgentgatewayBackendInterface {
	return &fakeAgentgatewayBackends{
		gentype.NewFakeClientWithList[*agentgateway.AgentgatewayBackend, *agentgateway.AgentgatewayBackendList](
			fake.Fake,
			namespace,
			agentgateway.SchemeGroupVersion.WithResource("agentgatewaybackends"),
			agentgateway.SchemeGroupVersion.WithKind("AgentgatewayBackend"),
			func() *agentgateway.AgentgatewayBackend { return &agentgateway.AgentgatewayBackend{} },
			func() *agentgateway.AgentgatewayBackendList { return &agentgateway.AgentgatewayBackendList{} },
			func(dst, src *agentgateway.AgentgatewayBackendList) { dst.ListMeta = src.ListMeta },
			func(list *agentgateway.AgentgatewayBackendList) []*agentgateway.AgentgatewayBackend {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *agentgateway.AgentgatewayBackendList, items []*agentgateway.AgentgatewayBackend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
