version: 2
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: controller
    main: ./cmd/kgateway
    binary: kgateway-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: sds
    main: ./cmd/sds
    binary: sds-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: envoyinit
    main: ./cmd/envoyinit
    binary: envoyinit-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers_v2:
  # 1. Controller Image (kgateway)
  - id: controller
    ids:
      - controller
    images:
      - "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.CONTROLLER_IMAGE_REPO }}"
    tags:
      - "{{ .Env.VERSION }}"
    dockerfile: cmd/kgateway/Dockerfile
    build_args:
      ENVOY_IMAGE: "{{ .Env.ENVOY_IMAGE }}"
    flags:
      - "--pull"
    platforms:
      - linux/amd64
      - linux/arm64

  # 2. agentgateway Controller Image
  - id: agentgateway
    ids:
      - controller
    images:
      - "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.AGENTGATEWAY_IMAGE_REPO }}"
    tags:
      - "{{ .Env.VERSION }}"
    dockerfile: cmd/kgateway/Dockerfile.agentgateway
    flags:
      - "--pull"
    platforms:
      - linux/amd64
      - linux/arm64

  # 3. SDS Image
  - id: sds
    ids:
      - sds
    images:
      - "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.SDS_IMAGE_REPO }}"
    tags:
      - "{{ .Env.VERSION }}"
    dockerfile: cmd/sds/Dockerfile
    build_args:
      BASE_IMAGE: "{{ .Env.ALPINE_BASE_IMAGE }}"
    flags:
      - "--pull"
    platforms:
      - linux/amd64
      - linux/arm64

  # 4. Envoy Init Image (envoy-wrapper)
  - id: envoyinit
    ids:
      - envoyinit
    images:
      - "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.ENVOYINIT_IMAGE_REPO }}"
    tags:
      - "{{ .Env.VERSION }}"
    dockerfile: cmd/envoyinit/Dockerfile
    build_args:
      ENVOY_IMAGE: "{{ .Env.ENVOY_IMAGE }}"
      ENTRYPOINT_SCRIPT: "/cmd/envoyinit/docker-entrypoint.sh"
      RUSTFORMATIONS_DIR: "/internal/envoyinit"
    flags:
      - "--pull"
      - "--cache-from=type=registry,ref={{ .Env.IMAGE_REGISTRY }}/envoy-wrapper-cache:latest"
      - "--cache-to=type=registry,ref={{ .Env.IMAGE_REGISTRY }}/envoy-wrapper-cache:latest,mode=max,ignore-error=true"
    extra_files:
      - cmd/envoyinit/docker-entrypoint.sh
      - internal/envoyinit
    platforms:
      - linux/amd64
      - linux/arm64
changelog:
  # Disable auto-generated changelog from git commits.
  # For real releases, we use --release-notes flag with our custom script output.
  # For main branch builds, we skip changelog entirely (same as release).
  disable: '{{ if isEnvSet "GORELEASER_DISABLE_RELEASE" }}{{ .Env.GORELEASER_DISABLE_RELEASE }}{{ else }}false{{ end }}'
release:
  disable: '{{ if isEnvSet "GORELEASER_DISABLE_RELEASE" }}{{ .Env.GORELEASER_DISABLE_RELEASE }}{{ else }}false{{ end }}'
  prerelease: "auto"
  mode: "replace"
  replace_existing_artifacts: true
  target_commitish: "{{ .FullCommit }}"
  header: |
    {{ if eq .Env.VERSION "v2.2.0-main" }}
    🚀 Rolling main build of kgateway!
    ---
    It includes the latest changes but may be unstable. Use it for testing and providing feedback.
    {{ else }}
    🎉 Welcome to the {{ .Env.VERSION }} release of the kgateway project!
    ---
    {{ end }}
  footer: |
    ## Installation

    The kgateway project is available as a Helm chart and docker images.

    ### Helm Charts

    The Helm charts are available at:
    * [{{ .Env.VANITY_REGISTRY }}/charts/kgateway]({{ .Env.VANITY_REGISTRY }}/charts/kgateway).
    * [{{ .Env.AGW_VANITY_REGISTRY }}/charts/agentgateway]({{ .Env.AGW_VANITY_REGISTRY }}/charts/agentgateway).

    ### Docker Images

    The docker images are available at:

    - {{ .Env.VANITY_REGISTRY }}/{{ .Env.CONTROLLER_IMAGE_REPO }}:{{ .Env.VERSION }}
    - {{ .Env.VANITY_REGISTRY }}/{{ .Env.SDS_IMAGE_REPO }}:{{ .Env.VERSION }}
    - {{ .Env.VANITY_REGISTRY }}/{{ .Env.ENVOYINIT_IMAGE_REPO }}:{{ .Env.VERSION }}
    - {{ .Env.AGW_VANITY_REGISTRY }}/{{ .Env.AGENTGATEWAY_IMAGE_REPO }}:{{ .Env.VERSION }}

    ## Quickstart

    Try installing this release:
    ```
    helm install kgateway-crds oci://{{ .Env.VANITY_REGISTRY }}/charts/kgateway-crds --version {{ .Env.VERSION }} --namespace kgateway-system --create-namespace
    helm install kgateway oci://{{ .Env.VANITY_REGISTRY }}/charts/kgateway --version {{ .Env.VERSION }} --namespace kgateway-system --create-namespace
    helm install agentgateway-crds oci://{{ .Env.AGW_VANITY_REGISTRY }}/charts/agentgateway-crds --version {{ .Env.VERSION }} --namespace agentgateway-system --create-namespace
    helm install agentgateway oci://{{ .Env.AGW_VANITY_REGISTRY }}/charts/agentgateway --version {{ .Env.VERSION }} --namespace agentgateway-system --create-namespace
    ```

    For detailed installation instructions and next steps, please visit our [quickstart guide](https://kgateway.dev/docs/quickstart/).
