// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackendConfigPoliciesGetter has a method to return a BackendConfigPolicyInterface.
// A group's client should implement this interface.
type BackendConfigPoliciesGetter interface {
	BackendConfigPolicies(namespace string) BackendConfigPolicyInterface
}

// BackendConfigPolicyInterface has methods to work with BackendConfigPolicy resources.
type BackendConfigPolicyInterface interface {
	Create(ctx context.Context, backendConfigPolicy *v1alpha1kgateway.BackendConfigPolicy, opts v1.CreateOptions) (*v1alpha1kgateway.BackendConfigPolicy, error)
	Update(ctx context.Context, backendConfigPolicy *v1alpha1kgateway.BackendConfigPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.BackendConfigPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backendConfigPolicy *v1alpha1kgateway.BackendConfigPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.BackendConfigPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.BackendConfigPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.BackendConfigPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.BackendConfigPolicy, err error)
	BackendConfigPolicyExpansion
}

// backendConfigPolicies implements BackendConfigPolicyInterface
type backendConfigPolicies struct {
	*gentype.ClientWithList[*v1alpha1kgateway.BackendConfigPolicy, *v1alpha1kgateway.BackendConfigPolicyList]
}

// newBackendConfigPolicies returns a BackendConfigPolicies
func newBackendConfigPolicies(c *GatewayKgatewayClient, namespace string) *backendConfigPolicies {
	return &backendConfigPolicies{
		gentype.NewClientWithList[*v1alpha1kgateway.BackendConfigPolicy, *v1alpha1kgateway.BackendConfigPolicyList](
			"backendconfigpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.BackendConfigPolicy { return &v1alpha1kgateway.BackendConfigPolicy{} },
			func() *v1alpha1kgateway.BackendConfigPolicyList { return &v1alpha1kgateway.BackendConfigPolicyList{} },
		),
	}
}
