// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackendsGetter has a method to return a BackendInterface.
// A group's client should implement this interface.
type BackendsGetter interface {
	Backends(namespace string) BackendInterface
}

// BackendInterface has methods to work with Backend resources.
type BackendInterface interface {
	Create(ctx context.Context, backend *v1alpha1kgateway.Backend, opts v1.CreateOptions) (*v1alpha1kgateway.Backend, error)
	Update(ctx context.Context, backend *v1alpha1kgateway.Backend, opts v1.UpdateOptions) (*v1alpha1kgateway.Backend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backend *v1alpha1kgateway.Backend, opts v1.UpdateOptions) (*v1alpha1kgateway.Backend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.Backend, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.BackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.Backend, err error)
	BackendExpansion
}

// backends implements BackendInterface
type backends struct {
	*gentype.ClientWithList[*v1alpha1kgateway.Backend, *v1alpha1kgateway.BackendList]
}

// newBackends returns a Backends
func newBackends(c *GatewayKgatewayClient, namespace string) *backends {
	return &backends{
		gentype.NewClientWithList[*v1alpha1kgateway.Backend, *v1alpha1kgateway.BackendList](
			"backends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.Backend { return &v1alpha1kgateway.Backend{} },
			func() *v1alpha1kgateway.BackendList { return &v1alpha1kgateway.BackendList{} },
		),
	}
}
