// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayParametersGetter has a method to return a GatewayParametersInterface.
// A group's client should implement this interface.
type GatewayParametersGetter interface {
	GatewayParameters(namespace string) GatewayParametersInterface
}

// GatewayParametersInterface has methods to work with GatewayParameters resources.
type GatewayParametersInterface interface {
	Create(ctx context.Context, gatewayParameters *v1alpha1kgateway.GatewayParameters, opts v1.CreateOptions) (*v1alpha1kgateway.GatewayParameters, error)
	Update(ctx context.Context, gatewayParameters *v1alpha1kgateway.GatewayParameters, opts v1.UpdateOptions) (*v1alpha1kgateway.GatewayParameters, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayParameters *v1alpha1kgateway.GatewayParameters, opts v1.UpdateOptions) (*v1alpha1kgateway.GatewayParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.GatewayParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.GatewayParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.GatewayParameters, err error)
	GatewayParametersExpansion
}

// gatewayParameters implements GatewayParametersInterface
type gatewayParameters struct {
	*gentype.ClientWithList[*v1alpha1kgateway.GatewayParameters, *v1alpha1kgateway.GatewayParametersList]
}

// newGatewayParameters returns a GatewayParameters
func newGatewayParameters(c *GatewayKgatewayClient, namespace string) *gatewayParameters {
	return &gatewayParameters{
		gentype.NewClientWithList[*v1alpha1kgateway.GatewayParameters, *v1alpha1kgateway.GatewayParametersList](
			"gatewayparameters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.GatewayParameters { return &v1alpha1kgateway.GatewayParameters{} },
			func() *v1alpha1kgateway.GatewayParametersList { return &v1alpha1kgateway.GatewayParametersList{} },
		),
	}
}
