// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayExtensionsGetter has a method to return a GatewayExtensionInterface.
// A group's client should implement this interface.
type GatewayExtensionsGetter interface {
	GatewayExtensions(namespace string) GatewayExtensionInterface
}

// GatewayExtensionInterface has methods to work with GatewayExtension resources.
type GatewayExtensionInterface interface {
	Create(ctx context.Context, gatewayExtension *v1alpha1kgateway.GatewayExtension, opts v1.CreateOptions) (*v1alpha1kgateway.GatewayExtension, error)
	Update(ctx context.Context, gatewayExtension *v1alpha1kgateway.GatewayExtension, opts v1.UpdateOptions) (*v1alpha1kgateway.GatewayExtension, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayExtension *v1alpha1kgateway.GatewayExtension, opts v1.UpdateOptions) (*v1alpha1kgateway.GatewayExtension, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.GatewayExtension, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.GatewayExtensionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.GatewayExtension, err error)
	GatewayExtensionExpansion
}

// gatewayExtensions implements GatewayExtensionInterface
type gatewayExtensions struct {
	*gentype.ClientWithList[*v1alpha1kgateway.GatewayExtension, *v1alpha1kgateway.GatewayExtensionList]
}

// newGatewayExtensions returns a GatewayExtensions
func newGatewayExtensions(c *GatewayKgatewayClient, namespace string) *gatewayExtensions {
	return &gatewayExtensions{
		gentype.NewClientWithList[*v1alpha1kgateway.GatewayExtension, *v1alpha1kgateway.GatewayExtensionList](
			"gatewayextensions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.GatewayExtension { return &v1alpha1kgateway.GatewayExtension{} },
			func() *v1alpha1kgateway.GatewayExtensionList { return &v1alpha1kgateway.GatewayExtensionList{} },
		),
	}
}
