// Code generated by client-gen. DO NOT EDIT.

package kgateway

type BackendExpansion interface{}

type BackendConfigPolicyExpansion interface{}

type DirectResponseExpansion interface{}

type GatewayExtensionExpansion interface{}

type GatewayParametersExpansion interface{}

type HTTPListenerPolicyExpansion interface{}

type ListenerPolicyExpansion interface{}

type TrafficPolicyExpansion interface{}
