// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HTTPListenerPoliciesGetter has a method to return a HTTPListenerPolicyInterface.
// A group's client should implement this interface.
type HTTPListenerPoliciesGetter interface {
	HTTPListenerPolicies(namespace string) HTTPListenerPolicyInterface
}

// HTTPListenerPolicyInterface has methods to work with HTTPListenerPolicy resources.
type HTTPListenerPolicyInterface interface {
	Create(ctx context.Context, hTTPListenerPolicy *v1alpha1kgateway.HTTPListenerPolicy, opts v1.CreateOptions) (*v1alpha1kgateway.HTTPListenerPolicy, error)
	Update(ctx context.Context, hTTPListenerPolicy *v1alpha1kgateway.HTTPListenerPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.HTTPListenerPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hTTPListenerPolicy *v1alpha1kgateway.HTTPListenerPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.HTTPListenerPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.HTTPListenerPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.HTTPListenerPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.HTTPListenerPolicy, err error)
	HTTPListenerPolicyExpansion
}

// hTTPListenerPolicies implements HTTPListenerPolicyInterface
type hTTPListenerPolicies struct {
	*gentype.ClientWithList[*v1alpha1kgateway.HTTPListenerPolicy, *v1alpha1kgateway.HTTPListenerPolicyList]
}

// newHTTPListenerPolicies returns a HTTPListenerPolicies
func newHTTPListenerPolicies(c *GatewayKgatewayClient, namespace string) *hTTPListenerPolicies {
	return &hTTPListenerPolicies{
		gentype.NewClientWithList[*v1alpha1kgateway.HTTPListenerPolicy, *v1alpha1kgateway.HTTPListenerPolicyList](
			"httplistenerpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.HTTPListenerPolicy { return &v1alpha1kgateway.HTTPListenerPolicy{} },
			func() *v1alpha1kgateway.HTTPListenerPolicyList { return &v1alpha1kgateway.HTTPListenerPolicyList{} },
		),
	}
}
