// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ListenerPoliciesGetter has a method to return a ListenerPolicyInterface.
// A group's client should implement this interface.
type ListenerPoliciesGetter interface {
	ListenerPolicies(namespace string) ListenerPolicyInterface
}

// ListenerPolicyInterface has methods to work with ListenerPolicy resources.
type ListenerPolicyInterface interface {
	Create(ctx context.Context, listenerPolicy *v1alpha1kgateway.ListenerPolicy, opts v1.CreateOptions) (*v1alpha1kgateway.ListenerPolicy, error)
	Update(ctx context.Context, listenerPolicy *v1alpha1kgateway.ListenerPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.ListenerPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, listenerPolicy *v1alpha1kgateway.ListenerPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.ListenerPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.ListenerPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.ListenerPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.ListenerPolicy, err error)
	ListenerPolicyExpansion
}

// listenerPolicies implements ListenerPolicyInterface
type listenerPolicies struct {
	*gentype.ClientWithList[*v1alpha1kgateway.ListenerPolicy, *v1alpha1kgateway.ListenerPolicyList]
}

// newListenerPolicies returns a ListenerPolicies
func newListenerPolicies(c *GatewayKgatewayClient, namespace string) *listenerPolicies {
	return &listenerPolicies{
		gentype.NewClientWithList[*v1alpha1kgateway.ListenerPolicy, *v1alpha1kgateway.ListenerPolicyList](
			"listenerpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.ListenerPolicy { return &v1alpha1kgateway.ListenerPolicy{} },
			func() *v1alpha1kgateway.ListenerPolicyList { return &v1alpha1kgateway.ListenerPolicyList{} },
		),
	}
}
