// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	context "context"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TrafficPoliciesGetter has a method to return a TrafficPolicyInterface.
// A group's client should implement this interface.
type TrafficPoliciesGetter interface {
	TrafficPolicies(namespace string) TrafficPolicyInterface
}

// TrafficPolicyInterface has methods to work with TrafficPolicy resources.
type TrafficPolicyInterface interface {
	Create(ctx context.Context, trafficPolicy *v1alpha1kgateway.TrafficPolicy, opts v1.CreateOptions) (*v1alpha1kgateway.TrafficPolicy, error)
	Update(ctx context.Context, trafficPolicy *v1alpha1kgateway.TrafficPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.TrafficPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, trafficPolicy *v1alpha1kgateway.TrafficPolicy, opts v1.UpdateOptions) (*v1alpha1kgateway.TrafficPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1kgateway.TrafficPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1kgateway.TrafficPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1kgateway.TrafficPolicy, err error)
	TrafficPolicyExpansion
}

// trafficPolicies implements TrafficPolicyInterface
type trafficPolicies struct {
	*gentype.ClientWithList[*v1alpha1kgateway.TrafficPolicy, *v1alpha1kgateway.TrafficPolicyList]
}

// newTrafficPolicies returns a TrafficPolicies
func newTrafficPolicies(c *GatewayKgatewayClient, namespace string) *trafficPolicies {
	return &trafficPolicies{
		gentype.NewClientWithList[*v1alpha1kgateway.TrafficPolicy, *v1alpha1kgateway.TrafficPolicyList](
			"trafficpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1kgateway.TrafficPolicy { return &v1alpha1kgateway.TrafficPolicy{} },
			func() *v1alpha1kgateway.TrafficPolicyList { return &v1alpha1kgateway.TrafficPolicyList{} },
		),
	}
}
