// Code generated by client-gen. DO NOT EDIT.

package kgateway

import (
	http "net/http"

	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type GatewayKgatewayInterface interface {
	RESTClient() rest.Interface
	BackendsGetter
	BackendConfigPoliciesGetter
	DirectResponsesGetter
	GatewayExtensionsGetter
	GatewayParametersGetter
	HTTPListenerPoliciesGetter
	ListenerPoliciesGetter
	TrafficPoliciesGetter
}

// GatewayKgatewayClient is used to interact with features provided by the gateway.kgateway.dev group.
type GatewayKgatewayClient struct {
	restClient rest.Interface
}

func (c *GatewayKgatewayClient) Backends(namespace string) BackendInterface {
	return newBackends(c, namespace)
}

func (c *GatewayKgatewayClient) BackendConfigPolicies(namespace string) BackendConfigPolicyInterface {
	return newBackendConfigPolicies(c, namespace)
}

func (c *GatewayKgatewayClient) DirectResponses(namespace string) DirectResponseInterface {
	return newDirectResponses(c, namespace)
}

func (c *GatewayKgatewayClient) GatewayExtensions(namespace string) GatewayExtensionInterface {
	return newGatewayExtensions(c, namespace)
}

func (c *GatewayKgatewayClient) GatewayParameters(namespace string) GatewayParametersInterface {
	return newGatewayParameters(c, namespace)
}

func (c *GatewayKgatewayClient) HTTPListenerPolicies(namespace string) HTTPListenerPolicyInterface {
	return newHTTPListenerPolicies(c, namespace)
}

func (c *GatewayKgatewayClient) ListenerPolicies(namespace string) ListenerPolicyInterface {
	return newListenerPolicies(c, namespace)
}

func (c *GatewayKgatewayClient) TrafficPolicies(namespace string) TrafficPolicyInterface {
	return newTrafficPolicies(c, namespace)
}

// NewForConfig creates a new GatewayKgatewayClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*GatewayKgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new GatewayKgatewayClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*GatewayKgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &GatewayKgatewayClient{client}, nil
}

// NewForConfigOrDie creates a new GatewayKgatewayClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *GatewayKgatewayClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new GatewayKgatewayClient for the given RESTClient.
func New(c rest.Interface) *GatewayKgatewayClient {
	return &GatewayKgatewayClient{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := v1alpha1kgateway.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *GatewayKgatewayClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
