apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /foo
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.kgateway.dev
        kind: TrafficPolicy
        name: api-key-auth-selector
---
# Secret with different labels that don't match the selector
apiVersion: v1
kind: Secret
metadata:
  name: same-ns-secret
  namespace: default
  labels:
    app: other
    type: different
type: Opaque
data:
  client1: ay0xMjM=
---
# Secret with matching labels but in other namespace (no reference grant)
apiVersion: v1
kind: Secret
metadata:
  name: other-ns-secret
  namespace: other
  labels:
    app: api-keys
    type: authentication
type: Opaque
data:
  client1: ay0xMjM=
---
# TrafficPolicy with API key authentication using SecretSelector with no matching secrets
# This should result in an error status because no secrets match the selector
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: api-key-auth-selector
  namespace: default
spec:
  targetRefs:
  - name: example-route
    kind: HTTPRoute
    group: gateway.networking.k8s.io
  apiKeyAuth:
    keySources:
    - header: "x-api-key"
    forwardCredential: false
    clientIdHeader: "x-authenticated-client"
    secretSelector:
      matchLabels:
        app: api-keys
        type: authentication
---
# Test service
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: default
spec:
  selector:
    app: example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

