apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /status
  - backendRefs:
    - name: example-svc
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /get
---
# Gateway-level API key secret
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-gateway
  namespace: default
type: Opaque
data:
  client1: ay0xMjM=
  client2: ay00NTY=
---
# Route-level API key secret (different from gateway-level)
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-route
  namespace: default
type: Opaque
data:
  client3: ay03ODk=
  client4: ay05OTk=
---
# TrafficPolicy with API key authentication at gateway level
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: api-key-auth-gateway
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example-gateway
  apiKeyAuth:
    keySources:
    - header: "api-key"
    forwardCredential: false
    secretRef:
      name: api-keys-gateway
---
# TrafficPolicy with API key authentication at route level (overrides gateway-level)
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: api-key-auth-route-override
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  apiKeyAuth:
    keySources:
    - header: "x-api-key"
    forwardCredential: true
    secretRef:
      name: api-keys-route
---
# Test service
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: default
spec:
  selector:
    app: example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

