# This test contains a parent route that delegates to a child route. A traffic policy targets
# the parent route.
#
# Input:
# - Parent infra/example-route:
#   - Delegate /a to routes in "a" namespace
#   - Everything else goes to infra/example-svc
# - Child a/route-a1:
#   - inherits timeouts and retry from parent
# - Child a/route-a2:
#   - overrides timeouts and retry of parent
#
# - Parent infra/foo-route:
#   - Delegate /b to routes in "b" namespace
#   - Uses ShallowMergePreferParent for inherited policies
# - Child b/route-b:
#   - inherits timeouts and retry from parent
#
# Expected output routes:
# - /a/1 -> parent's timeout and retry
# - /a/2 -> route-a2's timeout and retry
# - /b/1 -> parent's timeout and retry
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a
    timeouts:
      request: 5s
    retry:
      attempts: 3
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a1
  namespace: a
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - name: svc-a
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a2
  namespace: a
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/2
    backendRefs:
    - name: svc-a
      port: 8080
    timeouts:
      request: 10s
    retry:
      attempts: 5
      codes:
        - 503
      backoff: 1s
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo-route
  namespace: infra
  annotations:
    kgateway.dev/inherited-policy-priority: ShallowMergePreferParent
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "foo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /b
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: b
    timeouts:
      request: 5s
    retry:
      attempts: 3      
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-b
  namespace: b
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /b/1
    backendRefs:
    - name: svc-b
      port: 8080
    timeouts:
      request: 10s
    retry:
      attempts: 5
