// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GRPCRetryPolicyApplyConfiguration represents a declarative configuration of the GRPCRetryPolicy type for use
// with apply.
type GRPCRetryPolicyApplyConfiguration struct {
	Attempts *int32                              `json:"attempts,omitempty"`
	Backoff  *GRPCRetryBackoffApplyConfiguration `json:"backoff,omitempty"`
}

// GRPCRetryPolicyApplyConfiguration constructs a declarative configuration of the GRPCRetryPolicy type for use with
// apply.
func GRPCRetryPolicy() *GRPCRetryPolicyApplyConfiguration {
	return &GRPCRetryPolicyApplyConfiguration{}
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *GRPCRetryPolicyApplyConfiguration) WithAttempts(value int32) *GRPCRetryPolicyApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithBackoff sets the Backoff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backoff field is set to the value of the last call.
func (b *GRPCRetryPolicyApplyConfiguration) WithBackoff(value *GRPCRetryBackoffApplyConfiguration) *GRPCRetryPolicyApplyConfiguration {
	b.Backoff = value
	return b
}
