// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GRPCRetryBackoffApplyConfiguration represents a declarative configuration of the GRPCRetryBackoff type for use
// with apply.
type GRPCRetryBackoffApplyConfiguration struct {
	BaseInterval *v1.Duration `json:"baseInterval,omitempty"`
	MaxInterval  *v1.Duration `json:"maxInterval,omitempty"`
}

// GRPCRetryBackoffApplyConfiguration constructs a declarative configuration of the GRPCRetryBackoff type for use with
// apply.
func GRPCRetryBackoff() *GRPCRetryBackoffApplyConfiguration {
	return &GRPCRetryBackoffApplyConfiguration{}
}

// WithBaseInterval sets the BaseInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseInterval field is set to the value of the last call.
func (b *GRPCRetryBackoffApplyConfiguration) WithBaseInterval(value v1.Duration) *GRPCRetryBackoffApplyConfiguration {
	b.BaseInterval = &value
	return b
}

// WithMaxInterval sets the MaxInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxInterval field is set to the value of the last call.
func (b *GRPCRetryBackoffApplyConfiguration) WithMaxInterval(value v1.Duration) *GRPCRetryBackoffApplyConfiguration {
	b.MaxInterval = &value
	return b
}
