kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: kgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    hostname: "www.example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - name: example-svc
          port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: default
type: Opaque
data:
  .htpasswd: dXNlcjE6e1NIQX1XNnBoNU1tNVB6OEdnaVVMYlBnekczN21qOWc9CnVzZXIyOntTSEF9Tmt2Zkx0ZDZoVVRUdHhHZ08ybnVyY3hqeWRjPQo=
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: basic-auth-policy
  namespace: default
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: example-route
  basicAuth:
    secretRef:
      name: basic-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: default
spec:
  selector:
    test: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: test
