// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayBackends implements AgentgatewayBackendInterface
type fakeAgentgatewayBackends struct {
	*gentype.FakeClientWithList[*v1alpha1.AgentgatewayBackend, *v1alpha1.AgentgatewayBackendList]
	Fake *FakeGatewayV1alpha1
}

func newFakeAgentgatewayBackends(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.AgentgatewayBackendInterface {
	return &fakeAgentgatewayBackends{
		gentype.NewFakeClientWithList[*v1alpha1.AgentgatewayBackend, *v1alpha1.AgentgatewayBackendList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("agentgatewaybackends"),
			v1alpha1.SchemeGroupVersion.WithKind("AgentgatewayBackend"),
			func() *v1alpha1.AgentgatewayBackend { return &v1alpha1.AgentgatewayBackend{} },
			func() *v1alpha1.AgentgatewayBackendList { return &v1alpha1.AgentgatewayBackendList{} },
			func(dst, src *v1alpha1.AgentgatewayBackendList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AgentgatewayBackendList) []*v1alpha1.AgentgatewayBackend {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AgentgatewayBackendList, items []*v1alpha1.AgentgatewayBackend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
