// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGatewayParameters implements GatewayParametersInterface
type fakeGatewayParameters struct {
	*gentype.FakeClientWithList[*v1alpha1.GatewayParameters, *v1alpha1.GatewayParametersList]
	Fake *FakeGatewayV1alpha1
}

func newFakeGatewayParameters(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.GatewayParametersInterface {
	return &fakeGatewayParameters{
		gentype.NewFakeClientWithList[*v1alpha1.GatewayParameters, *v1alpha1.GatewayParametersList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("gatewayparameters"),
			v1alpha1.SchemeGroupVersion.WithKind("GatewayParameters"),
			func() *v1alpha1.GatewayParameters { return &v1alpha1.GatewayParameters{} },
			func() *v1alpha1.GatewayParametersList { return &v1alpha1.GatewayParametersList{} },
			func(dst, src *v1alpha1.GatewayParametersList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GatewayParametersList) []*v1alpha1.GatewayParameters {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GatewayParametersList, items []*v1alpha1.GatewayParameters) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
