// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHTTPListenerPolicies implements HTTPListenerPolicyInterface
type fakeHTTPListenerPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.HTTPListenerPolicy, *v1alpha1.HTTPListenerPolicyList]
	Fake *FakeGatewayV1alpha1
}

func newFakeHTTPListenerPolicies(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.HTTPListenerPolicyInterface {
	return &fakeHTTPListenerPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.HTTPListenerPolicy, *v1alpha1.HTTPListenerPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("httplistenerpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("HTTPListenerPolicy"),
			func() *v1alpha1.HTTPListenerPolicy { return &v1alpha1.HTTPListenerPolicy{} },
			func() *v1alpha1.HTTPListenerPolicyList { return &v1alpha1.HTTPListenerPolicyList{} },
			func(dst, src *v1alpha1.HTTPListenerPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.HTTPListenerPolicyList) []*v1alpha1.HTTPListenerPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.HTTPListenerPolicyList, items []*v1alpha1.HTTPListenerPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
