// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeAgentgatewayPolicies implements AgentgatewayPolicyInterface
type fakeAgentgatewayPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.AgentgatewayPolicy, *v1alpha1.AgentgatewayPolicyList]
	Fake *FakeGatewayV1alpha1
}

func newFakeAgentgatewayPolicies(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.AgentgatewayPolicyInterface {
	return &fakeAgentgatewayPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.AgentgatewayPolicy, *v1alpha1.AgentgatewayPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("agentgatewaypolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("AgentgatewayPolicy"),
			func() *v1alpha1.AgentgatewayPolicy { return &v1alpha1.AgentgatewayPolicy{} },
			func() *v1alpha1.AgentgatewayPolicyList { return &v1alpha1.AgentgatewayPolicyList{} },
			func(dst, src *v1alpha1.AgentgatewayPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.AgentgatewayPolicyList) []*v1alpha1.AgentgatewayPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.AgentgatewayPolicyList, items []*v1alpha1.AgentgatewayPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
