// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeListenerPolicies implements ListenerPolicyInterface
type fakeListenerPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.ListenerPolicy, *v1alpha1.ListenerPolicyList]
	Fake *FakeGatewayV1alpha1
}

func newFakeListenerPolicies(fake *FakeGatewayV1alpha1, namespace string) apiv1alpha1.ListenerPolicyInterface {
	return &fakeListenerPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.ListenerPolicy, *v1alpha1.ListenerPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("listenerpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("ListenerPolicy"),
			func() *v1alpha1.ListenerPolicy { return &v1alpha1.ListenerPolicy{} },
			func() *v1alpha1.ListenerPolicyList { return &v1alpha1.ListenerPolicyList{} },
			func(dst, src *v1alpha1.ListenerPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ListenerPolicyList) []*v1alpha1.ListenerPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ListenerPolicyList, items []*v1alpha1.ListenerPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
