// Code generated by MockGen. DO NOT EDIT.
// Source: ./jwks_fetcher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jose "github.com/go-jose/go-jose/v4"
	gomock "github.com/golang/mock/gomock"
)

// MockJwksHttpClient is a mock of JwksHttpClient interface.
type MockJwksHttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockJwksHttpClientMockRecorder
}

// MockJwksHttpClientMockRecorder is the mock recorder for MockJwksHttpClient.
type MockJwksHttpClientMockRecorder struct {
	mock *MockJwksHttpClient
}

// NewMockJwksHttpClient creates a new mock instance.
func NewMockJwksHttpClient(ctrl *gomock.Controller) *MockJwksHttpClient {
	mock := &MockJwksHttpClient{ctrl: ctrl}
	mock.recorder = &MockJwksHttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwksHttpClient) EXPECT() *MockJwksHttpClientMockRecorder {
	return m.recorder
}

// FetchJwks mocks base method.
func (m *MockJwksHttpClient) FetchJwks(ctx context.Context, jwksURL string) (jose.JSONWebKeySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJwks", ctx, jwksURL)
	ret0, _ := ret[0].(jose.JSONWebKeySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJwks indicates an expected call of FetchJwks.
func (mr *MockJwksHttpClientMockRecorder) FetchJwks(ctx, jwksURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJwks", reflect.TypeOf((*MockJwksHttpClient)(nil).FetchJwks), ctx, jwksURL)
}
