// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayBackendsGetter has a method to return a AgentgatewayBackendInterface.
// A group's client should implement this interface.
type AgentgatewayBackendsGetter interface {
	AgentgatewayBackends(namespace string) AgentgatewayBackendInterface
}

// AgentgatewayBackendInterface has methods to work with AgentgatewayBackend resources.
type AgentgatewayBackendInterface interface {
	Create(ctx context.Context, agentgatewayBackend *apiv1alpha1.AgentgatewayBackend, opts v1.CreateOptions) (*apiv1alpha1.AgentgatewayBackend, error)
	Update(ctx context.Context, agentgatewayBackend *apiv1alpha1.AgentgatewayBackend, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayBackend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayBackend *apiv1alpha1.AgentgatewayBackend, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayBackend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.AgentgatewayBackend, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.AgentgatewayBackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.AgentgatewayBackend, err error)
	AgentgatewayBackendExpansion
}

// agentgatewayBackends implements AgentgatewayBackendInterface
type agentgatewayBackends struct {
	*gentype.ClientWithList[*apiv1alpha1.AgentgatewayBackend, *apiv1alpha1.AgentgatewayBackendList]
}

// newAgentgatewayBackends returns a AgentgatewayBackends
func newAgentgatewayBackends(c *GatewayV1alpha1Client, namespace string) *agentgatewayBackends {
	return &agentgatewayBackends{
		gentype.NewClientWithList[*apiv1alpha1.AgentgatewayBackend, *apiv1alpha1.AgentgatewayBackendList](
			"agentgatewaybackends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.AgentgatewayBackend { return &apiv1alpha1.AgentgatewayBackend{} },
			func() *apiv1alpha1.AgentgatewayBackendList { return &apiv1alpha1.AgentgatewayBackendList{} },
		),
	}
}
