// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayPoliciesGetter has a method to return a AgentgatewayPolicyInterface.
// A group's client should implement this interface.
type AgentgatewayPoliciesGetter interface {
	AgentgatewayPolicies(namespace string) AgentgatewayPolicyInterface
}

// AgentgatewayPolicyInterface has methods to work with AgentgatewayPolicy resources.
type AgentgatewayPolicyInterface interface {
	Create(ctx context.Context, agentgatewayPolicy *apiv1alpha1.AgentgatewayPolicy, opts v1.CreateOptions) (*apiv1alpha1.AgentgatewayPolicy, error)
	Update(ctx context.Context, agentgatewayPolicy *apiv1alpha1.AgentgatewayPolicy, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayPolicy *apiv1alpha1.AgentgatewayPolicy, opts v1.UpdateOptions) (*apiv1alpha1.AgentgatewayPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.AgentgatewayPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.AgentgatewayPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.AgentgatewayPolicy, err error)
	AgentgatewayPolicyExpansion
}

// agentgatewayPolicies implements AgentgatewayPolicyInterface
type agentgatewayPolicies struct {
	*gentype.ClientWithList[*apiv1alpha1.AgentgatewayPolicy, *apiv1alpha1.AgentgatewayPolicyList]
}

// newAgentgatewayPolicies returns a AgentgatewayPolicies
func newAgentgatewayPolicies(c *GatewayV1alpha1Client, namespace string) *agentgatewayPolicies {
	return &agentgatewayPolicies{
		gentype.NewClientWithList[*apiv1alpha1.AgentgatewayPolicy, *apiv1alpha1.AgentgatewayPolicyList](
			"agentgatewaypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.AgentgatewayPolicy { return &apiv1alpha1.AgentgatewayPolicy{} },
			func() *apiv1alpha1.AgentgatewayPolicyList { return &apiv1alpha1.AgentgatewayPolicyList{} },
		),
	}
}
