// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GatewayParametersGetter has a method to return a GatewayParametersInterface.
// A group's client should implement this interface.
type GatewayParametersGetter interface {
	GatewayParameters(namespace string) GatewayParametersInterface
}

// GatewayParametersInterface has methods to work with GatewayParameters resources.
type GatewayParametersInterface interface {
	Create(ctx context.Context, gatewayParameters *apiv1alpha1.GatewayParameters, opts v1.CreateOptions) (*apiv1alpha1.GatewayParameters, error)
	Update(ctx context.Context, gatewayParameters *apiv1alpha1.GatewayParameters, opts v1.UpdateOptions) (*apiv1alpha1.GatewayParameters, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayParameters *apiv1alpha1.GatewayParameters, opts v1.UpdateOptions) (*apiv1alpha1.GatewayParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.GatewayParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.GatewayParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.GatewayParameters, err error)
	GatewayParametersExpansion
}

// gatewayParameters implements GatewayParametersInterface
type gatewayParameters struct {
	*gentype.ClientWithList[*apiv1alpha1.GatewayParameters, *apiv1alpha1.GatewayParametersList]
}

// newGatewayParameters returns a GatewayParameters
func newGatewayParameters(c *GatewayV1alpha1Client, namespace string) *gatewayParameters {
	return &gatewayParameters{
		gentype.NewClientWithList[*apiv1alpha1.GatewayParameters, *apiv1alpha1.GatewayParametersList](
			"gatewayparameters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.GatewayParameters { return &apiv1alpha1.GatewayParameters{} },
			func() *apiv1alpha1.GatewayParametersList { return &apiv1alpha1.GatewayParametersList{} },
		),
	}
}
