// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AgentgatewayBackendExpansion interface{}

type AgentgatewayPolicyExpansion interface{}

type BackendExpansion interface{}

type BackendConfigPolicyExpansion interface{}

type DirectResponseExpansion interface{}

type GatewayExtensionExpansion interface{}

type GatewayParametersExpansion interface{}

type HTTPListenerPolicyExpansion interface{}

type ListenerPolicyExpansion interface{}

type TrafficPolicyExpansion interface{}
