// Code generated by client-gen. DO NOT EDIT.

package agentgateway

import (
	context "context"

	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayBackendsGetter has a method to return a AgentgatewayBackendInterface.
// A group's client should implement this interface.
type AgentgatewayBackendsGetter interface {
	AgentgatewayBackends(namespace string) AgentgatewayBackendInterface
}

// AgentgatewayBackendInterface has methods to work with AgentgatewayBackend resources.
type AgentgatewayBackendInterface interface {
	Create(ctx context.Context, agentgatewayBackend *v1alpha1agentgateway.AgentgatewayBackend, opts v1.CreateOptions) (*v1alpha1agentgateway.AgentgatewayBackend, error)
	Update(ctx context.Context, agentgatewayBackend *v1alpha1agentgateway.AgentgatewayBackend, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayBackend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayBackend *v1alpha1agentgateway.AgentgatewayBackend, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayBackend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1agentgateway.AgentgatewayBackend, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1agentgateway.AgentgatewayBackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1agentgateway.AgentgatewayBackend, err error)
	AgentgatewayBackendExpansion
}

// agentgatewayBackends implements AgentgatewayBackendInterface
type agentgatewayBackends struct {
	*gentype.ClientWithList[*v1alpha1agentgateway.AgentgatewayBackend, *v1alpha1agentgateway.AgentgatewayBackendList]
}

// newAgentgatewayBackends returns a AgentgatewayBackends
func newAgentgatewayBackends(c *GatewayAgentgatewayClient, namespace string) *agentgatewayBackends {
	return &agentgatewayBackends{
		gentype.NewClientWithList[*v1alpha1agentgateway.AgentgatewayBackend, *v1alpha1agentgateway.AgentgatewayBackendList](
			"agentgatewaybackends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1agentgateway.AgentgatewayBackend { return &v1alpha1agentgateway.AgentgatewayBackend{} },
			func() *v1alpha1agentgateway.AgentgatewayBackendList {
				return &v1alpha1agentgateway.AgentgatewayBackendList{}
			},
		),
	}
}
