// Code generated by client-gen. DO NOT EDIT.

package agentgateway

import (
	context "context"

	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayPoliciesGetter has a method to return a AgentgatewayPolicyInterface.
// A group's client should implement this interface.
type AgentgatewayPoliciesGetter interface {
	AgentgatewayPolicies(namespace string) AgentgatewayPolicyInterface
}

// AgentgatewayPolicyInterface has methods to work with AgentgatewayPolicy resources.
type AgentgatewayPolicyInterface interface {
	Create(ctx context.Context, agentgatewayPolicy *v1alpha1agentgateway.AgentgatewayPolicy, opts v1.CreateOptions) (*v1alpha1agentgateway.AgentgatewayPolicy, error)
	Update(ctx context.Context, agentgatewayPolicy *v1alpha1agentgateway.AgentgatewayPolicy, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayPolicy *v1alpha1agentgateway.AgentgatewayPolicy, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1agentgateway.AgentgatewayPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1agentgateway.AgentgatewayPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1agentgateway.AgentgatewayPolicy, err error)
	AgentgatewayPolicyExpansion
}

// agentgatewayPolicies implements AgentgatewayPolicyInterface
type agentgatewayPolicies struct {
	*gentype.ClientWithList[*v1alpha1agentgateway.AgentgatewayPolicy, *v1alpha1agentgateway.AgentgatewayPolicyList]
}

// newAgentgatewayPolicies returns a AgentgatewayPolicies
func newAgentgatewayPolicies(c *GatewayAgentgatewayClient, namespace string) *agentgatewayPolicies {
	return &agentgatewayPolicies{
		gentype.NewClientWithList[*v1alpha1agentgateway.AgentgatewayPolicy, *v1alpha1agentgateway.AgentgatewayPolicyList](
			"agentgatewaypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1agentgateway.AgentgatewayPolicy { return &v1alpha1agentgateway.AgentgatewayPolicy{} },
			func() *v1alpha1agentgateway.AgentgatewayPolicyList {
				return &v1alpha1agentgateway.AgentgatewayPolicyList{}
			},
		),
	}
}
