// Code generated by client-gen. DO NOT EDIT.

package agentgateway

import (
	context "context"

	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AgentgatewayParametersGetter has a method to return a AgentgatewayParametersInterface.
// A group's client should implement this interface.
type AgentgatewayParametersGetter interface {
	AgentgatewayParameters(namespace string) AgentgatewayParametersInterface
}

// AgentgatewayParametersInterface has methods to work with AgentgatewayParameters resources.
type AgentgatewayParametersInterface interface {
	Create(ctx context.Context, agentgatewayParameters *v1alpha1agentgateway.AgentgatewayParameters, opts v1.CreateOptions) (*v1alpha1agentgateway.AgentgatewayParameters, error)
	Update(ctx context.Context, agentgatewayParameters *v1alpha1agentgateway.AgentgatewayParameters, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayParameters, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, agentgatewayParameters *v1alpha1agentgateway.AgentgatewayParameters, opts v1.UpdateOptions) (*v1alpha1agentgateway.AgentgatewayParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1agentgateway.AgentgatewayParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1agentgateway.AgentgatewayParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1agentgateway.AgentgatewayParameters, err error)
	AgentgatewayParametersExpansion
}

// agentgatewayParameters implements AgentgatewayParametersInterface
type agentgatewayParameters struct {
	*gentype.ClientWithList[*v1alpha1agentgateway.AgentgatewayParameters, *v1alpha1agentgateway.AgentgatewayParametersList]
}

// newAgentgatewayParameters returns a AgentgatewayParameters
func newAgentgatewayParameters(c *GatewayAgentgatewayClient, namespace string) *agentgatewayParameters {
	return &agentgatewayParameters{
		gentype.NewClientWithList[*v1alpha1agentgateway.AgentgatewayParameters, *v1alpha1agentgateway.AgentgatewayParametersList](
			"agentgatewayparameters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1agentgateway.AgentgatewayParameters {
				return &v1alpha1agentgateway.AgentgatewayParameters{}
			},
			func() *v1alpha1agentgateway.AgentgatewayParametersList {
				return &v1alpha1agentgateway.AgentgatewayParametersList{}
			},
		),
	}
}
