// Code generated by client-gen. DO NOT EDIT.

package agentgateway

type AgentgatewayBackendExpansion interface{}

type AgentgatewayParametersExpansion interface{}

type AgentgatewayPolicyExpansion interface{}
