//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package agentgateway

import (
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/shared"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBackend) DeepCopyInto(out *AIBackend) {
	*out = *in
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityGroups != nil {
		in, out := &in.PriorityGroups, &out.PriorityGroups
		*out = make([]PriorityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBackend.
func (in *AIBackend) DeepCopy() *AIBackend {
	if in == nil {
		return nil
	}
	out := new(AIBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPromptEnrichment) DeepCopyInto(out *AIPromptEnrichment) {
	*out = *in
	if in.Prepend != nil {
		in, out := &in.Prepend, &out.Prepend
		*out = make([]Message, len(*in))
		copy(*out, *in)
	}
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = make([]Message, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPromptEnrichment.
func (in *AIPromptEnrichment) DeepCopy() *AIPromptEnrichment {
	if in == nil {
		return nil
	}
	out := new(AIPromptEnrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPromptGuard) DeepCopyInto(out *AIPromptGuard) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = make([]PromptguardRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = make([]PromptguardResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPromptGuard.
func (in *AIPromptGuard) DeepCopy() *AIPromptGuard {
	if in == nil {
		return nil
	}
	out := new(AIPromptGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIKeyAuthentication) DeepCopyInto(out *APIKeyAuthentication) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.SecretSelector != nil {
		in, out := &in.SecretSelector, &out.SecretSelector
		*out = new(SecretSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIKeyAuthentication.
func (in *APIKeyAuthentication) DeepCopy() *APIKeyAuthentication {
	if in == nil {
		return nil
	}
	out := new(APIKeyAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSGuardrailConfig) DeepCopyInto(out *AWSGuardrailConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSGuardrailConfig.
func (in *AWSGuardrailConfig) DeepCopy() *AWSGuardrailConfig {
	if in == nil {
		return nil
	}
	out := new(AWSGuardrailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLog) DeepCopyInto(out *AccessLog) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(LogTracingAttributes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLog.
func (in *AccessLog) DeepCopy() *AccessLog {
	if in == nil {
		return nil
	}
	out := new(AccessLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentExtAuthGRPC) DeepCopyInto(out *AgentExtAuthGRPC) {
	*out = *in
	if in.ContextExtensions != nil {
		in, out := &in.ContextExtensions, &out.ContextExtensions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestMetadata != nil {
		in, out := &in.RequestMetadata, &out.RequestMetadata
		*out = make(map[string]shared.CELExpression, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentExtAuthGRPC.
func (in *AgentExtAuthGRPC) DeepCopy() *AgentExtAuthGRPC {
	if in == nil {
		return nil
	}
	out := new(AgentExtAuthGRPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentExtAuthHTTP) DeepCopyInto(out *AgentExtAuthHTTP) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.Redirect != nil {
		in, out := &in.Redirect, &out.Redirect
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.AllowedRequestHeaders != nil {
		in, out := &in.AllowedRequestHeaders, &out.AllowedRequestHeaders
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
	if in.AddRequestHeaders != nil {
		in, out := &in.AddRequestHeaders, &out.AddRequestHeaders
		*out = make(map[string]shared.CELExpression, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowedResponseHeaders != nil {
		in, out := &in.AllowedResponseHeaders, &out.AllowedResponseHeaders
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
	if in.ResponseMetadata != nil {
		in, out := &in.ResponseMetadata, &out.ResponseMetadata
		*out = make(map[string]shared.CELExpression, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentExtAuthHTTP.
func (in *AgentExtAuthHTTP) DeepCopy() *AgentExtAuthHTTP {
	if in == nil {
		return nil
	}
	out := new(AgentExtAuthHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackend) DeepCopyInto(out *AgentgatewayBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackend.
func (in *AgentgatewayBackend) DeepCopy() *AgentgatewayBackend {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendList) DeepCopyInto(out *AgentgatewayBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentgatewayBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendList.
func (in *AgentgatewayBackendList) DeepCopy() *AgentgatewayBackendList {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendSpec) DeepCopyInto(out *AgentgatewayBackendSpec) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(AIBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.DynamicForwardProxy != nil {
		in, out := &in.DynamicForwardProxy, &out.DynamicForwardProxy
		*out = new(DynamicForwardProxyBackend)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(BackendFull)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendSpec.
func (in *AgentgatewayBackendSpec) DeepCopy() *AgentgatewayBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendStatus) DeepCopyInto(out *AgentgatewayBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendStatus.
func (in *AgentgatewayBackendStatus) DeepCopy() *AgentgatewayBackendStatus {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParameters) DeepCopyInto(out *AgentgatewayParameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParameters.
func (in *AgentgatewayParameters) DeepCopy() *AgentgatewayParameters {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayParameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersConfigs) DeepCopyInto(out *AgentgatewayParametersConfigs) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(AgentgatewayParametersLogging)
		**out = **in
	}
	if in.RawConfig != nil {
		in, out := &in.RawConfig, &out.RawConfig
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(Image)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(ShutdownSpec)
		**out = **in
	}
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(IstioSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersConfigs.
func (in *AgentgatewayParametersConfigs) DeepCopy() *AgentgatewayParametersConfigs {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersList) DeepCopyInto(out *AgentgatewayParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentgatewayParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersList.
func (in *AgentgatewayParametersList) DeepCopy() *AgentgatewayParametersList {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersLogging) DeepCopyInto(out *AgentgatewayParametersLogging) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersLogging.
func (in *AgentgatewayParametersLogging) DeepCopy() *AgentgatewayParametersLogging {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersOverlays) DeepCopyInto(out *AgentgatewayParametersOverlays) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalPodAutoscaler != nil {
		in, out := &in.HorizontalPodAutoscaler, &out.HorizontalPodAutoscaler
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersOverlays.
func (in *AgentgatewayParametersOverlays) DeepCopy() *AgentgatewayParametersOverlays {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersOverlays)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersSpec) DeepCopyInto(out *AgentgatewayParametersSpec) {
	*out = *in
	in.AgentgatewayParametersConfigs.DeepCopyInto(&out.AgentgatewayParametersConfigs)
	in.AgentgatewayParametersOverlays.DeepCopyInto(&out.AgentgatewayParametersOverlays)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersSpec.
func (in *AgentgatewayParametersSpec) DeepCopy() *AgentgatewayParametersSpec {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayParametersStatus) DeepCopyInto(out *AgentgatewayParametersStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayParametersStatus.
func (in *AgentgatewayParametersStatus) DeepCopy() *AgentgatewayParametersStatus {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayParametersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicy) DeepCopyInto(out *AgentgatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicy.
func (in *AgentgatewayPolicy) DeepCopy() *AgentgatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyList) DeepCopyInto(out *AgentgatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentgatewayPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyList.
func (in *AgentgatewayPolicyList) DeepCopy() *AgentgatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicySpec) DeepCopyInto(out *AgentgatewayPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]shared.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetSelectors != nil {
		in, out := &in.TargetSelectors, &out.TargetSelectors
		*out = make([]shared.LocalPolicyTargetSelectorWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frontend != nil {
		in, out := &in.Frontend, &out.Frontend
		*out = new(Frontend)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(Traffic)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(BackendFull)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicySpec.
func (in *AgentgatewayPolicySpec) DeepCopy() *AgentgatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicConfig) DeepCopyInto(out *AnthropicConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicConfig.
func (in *AnthropicConfig) DeepCopy() *AnthropicConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeAdd) DeepCopyInto(out *AttributeAdd) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeAdd.
func (in *AttributeAdd) DeepCopy() *AttributeAdd {
	if in == nil {
		return nil
	}
	out := new(AttributeAdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAuth) DeepCopyInto(out *AwsAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAuth.
func (in *AwsAuth) DeepCopy() *AwsAuth {
	if in == nil {
		return nil
	}
	out := new(AwsAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOpenAIConfig) DeepCopyInto(out *AzureOpenAIConfig) {
	*out = *in
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(ShortString)
		**out = **in
	}
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(TinyString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOpenAIConfig.
func (in *AzureOpenAIConfig) DeepCopy() *AzureOpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(AzureOpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAI) DeepCopyInto(out *BackendAI) {
	*out = *in
	if in.PromptEnrichment != nil {
		in, out := &in.PromptEnrichment, &out.PromptEnrichment
		*out = new(AIPromptEnrichment)
		(*in).DeepCopyInto(*out)
	}
	if in.PromptGuard != nil {
		in, out := &in.PromptGuard, &out.PromptGuard
		*out = new(AIPromptGuard)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]FieldDefault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]FieldDefault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelAliases != nil {
		in, out := &in.ModelAliases, &out.ModelAliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PromptCaching != nil {
		in, out := &in.PromptCaching, &out.PromptCaching
		*out = new(PromptCachingConfig)
		**out = **in
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(map[string]RouteType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAI.
func (in *BackendAI) DeepCopy() *BackendAI {
	if in == nil {
		return nil
	}
	out := new(BackendAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAuth) DeepCopyInto(out *BackendAuth) {
	*out = *in
	if in.InlineKey != nil {
		in, out := &in.InlineKey, &out.InlineKey
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Passthrough != nil {
		in, out := &in.Passthrough, &out.Passthrough
		*out = new(BackendAuthPassthrough)
		**out = **in
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AwsAuth)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GcpAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAuth.
func (in *BackendAuth) DeepCopy() *BackendAuth {
	if in == nil {
		return nil
	}
	out := new(BackendAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAuthPassthrough) DeepCopyInto(out *BackendAuthPassthrough) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAuthPassthrough.
func (in *BackendAuthPassthrough) DeepCopy() *BackendAuthPassthrough {
	if in == nil {
		return nil
	}
	out := new(BackendAuthPassthrough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendFull) DeepCopyInto(out *BackendFull) {
	*out = *in
	in.BackendSimple.DeepCopyInto(&out.BackendSimple)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(BackendAI)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(BackendMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendFull.
func (in *BackendFull) DeepCopy() *BackendFull {
	if in == nil {
		return nil
	}
	out := new(BackendFull)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendHTTP) DeepCopyInto(out *BackendHTTP) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(HTTPVersion)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendHTTP.
func (in *BackendHTTP) DeepCopy() *BackendHTTP {
	if in == nil {
		return nil
	}
	out := new(BackendHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendMCP) DeepCopyInto(out *BackendMCP) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(shared.Authorization)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(MCPAuthentication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendMCP.
func (in *BackendMCP) DeepCopy() *BackendMCP {
	if in == nil {
		return nil
	}
	out := new(BackendMCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendSimple) DeepCopyInto(out *BackendSimple) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(BackendTCP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(BackendTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(BackendHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(BackendAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendSimple.
func (in *BackendSimple) DeepCopy() *BackendSimple {
	if in == nil {
		return nil
	}
	out := new(BackendSimple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTCP) DeepCopyInto(out *BackendTCP) {
	*out = *in
	if in.Keepalive != nil {
		in, out := &in.Keepalive, &out.Keepalive
		*out = new(Keepalive)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTCP.
func (in *BackendTCP) DeepCopy() *BackendTCP {
	if in == nil {
		return nil
	}
	out := new(BackendTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTLS) DeepCopyInto(out *BackendTLS) {
	*out = *in
	if in.MtlsCertificateRef != nil {
		in, out := &in.MtlsCertificateRef, &out.MtlsCertificateRef
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CACertificateRefs != nil {
		in, out := &in.CACertificateRefs, &out.CACertificateRefs
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(InsecureTLSMode)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(SNI)
		**out = **in
	}
	if in.VerifySubjectAltNames != nil {
		in, out := &in.VerifySubjectAltNames, &out.VerifySubjectAltNames
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
	if in.AlpnProtocols != nil {
		in, out := &in.AlpnProtocols, &out.AlpnProtocols
		*out = new([]TinyString)
		if **in != nil {
			in, out := *in, *out
			*out = make([]TinyString, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTLS.
func (in *BackendTLS) DeepCopy() *BackendTLS {
	if in == nil {
		return nil
	}
	out := new(BackendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendWithAI) DeepCopyInto(out *BackendWithAI) {
	*out = *in
	in.BackendSimple.DeepCopyInto(&out.BackendSimple)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(BackendAI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendWithAI.
func (in *BackendWithAI) DeepCopy() *BackendWithAI {
	if in == nil {
		return nil
	}
	out := new(BackendWithAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendWithMCP) DeepCopyInto(out *BackendWithMCP) {
	*out = *in
	in.BackendSimple.DeepCopyInto(&out.BackendSimple)
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(BackendMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendWithMCP.
func (in *BackendWithMCP) DeepCopy() *BackendWithMCP {
	if in == nil {
		return nil
	}
	out := new(BackendWithMCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthentication) DeepCopyInto(out *BasicAuthentication) {
	*out = *in
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthentication.
func (in *BasicAuthentication) DeepCopy() *BasicAuthentication {
	if in == nil {
		return nil
	}
	out := new(BasicAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockConfig) DeepCopyInto(out *BedrockConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
	if in.Guardrail != nil {
		in, out := &in.Guardrail, &out.Guardrail
		*out = new(AWSGuardrailConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockConfig.
func (in *BedrockConfig) DeepCopy() *BedrockConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORS) DeepCopyInto(out *CORS) {
	*out = *in
	if in.HTTPCORSFilter != nil {
		in, out := &in.HTTPCORSFilter, &out.HTTPCORSFilter
		*out = new(apisv1.HTTPCORSFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORS.
func (in *CORS) DeepCopy() *CORS {
	if in == nil {
		return nil
	}
	out := new(CORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSRF) DeepCopyInto(out *CSRF) {
	*out = *in
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSRF.
func (in *CSRF) DeepCopy() *CSRF {
	if in == nil {
		return nil
	}
	out := new(CSRF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResponse) DeepCopyInto(out *CustomResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResponse.
func (in *CustomResponse) DeepCopy() *CustomResponse {
	if in == nil {
		return nil
	}
	out := new(CustomResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectResponse) DeepCopyInto(out *DirectResponse) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectResponse.
func (in *DirectResponse) DeepCopy() *DirectResponse {
	if in == nil {
		return nil
	}
	out := new(DirectResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicForwardProxyBackend) DeepCopyInto(out *DynamicForwardProxyBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicForwardProxyBackend.
func (in *DynamicForwardProxyBackend) DeepCopy() *DynamicForwardProxyBackend {
	if in == nil {
		return nil
	}
	out := new(DynamicForwardProxyBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtAuth) DeepCopyInto(out *ExtAuth) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(AgentExtAuthGRPC)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(AgentExtAuthHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.ForwardBody != nil {
		in, out := &in.ForwardBody, &out.ForwardBody
		*out = new(ExtAuthBody)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtAuth.
func (in *ExtAuth) DeepCopy() *ExtAuth {
	if in == nil {
		return nil
	}
	out := new(ExtAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtAuthBody) DeepCopyInto(out *ExtAuthBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtAuthBody.
func (in *ExtAuthBody) DeepCopy() *ExtAuthBody {
	if in == nil {
		return nil
	}
	out := new(ExtAuthBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtProc) DeepCopyInto(out *ExtProc) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtProc.
func (in *ExtProc) DeepCopy() *ExtProc {
	if in == nil {
		return nil
	}
	out := new(ExtProc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldDefault) DeepCopyInto(out *FieldDefault) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldDefault.
func (in *FieldDefault) DeepCopy() *FieldDefault {
	if in == nil {
		return nil
	}
	out := new(FieldDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Frontend) DeepCopyInto(out *Frontend) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(FrontendTCP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(FrontendTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(FrontendHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = new(AccessLog)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(Tracing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Frontend.
func (in *Frontend) DeepCopy() *Frontend {
	if in == nil {
		return nil
	}
	out := new(Frontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendHTTP) DeepCopyInto(out *FrontendHTTP) {
	*out = *in
	if in.MaxBufferSize != nil {
		in, out := &in.MaxBufferSize, &out.MaxBufferSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP1MaxHeaders != nil {
		in, out := &in.HTTP1MaxHeaders, &out.HTTP1MaxHeaders
		*out = new(int32)
		**out = **in
	}
	if in.HTTP1IdleTimeout != nil {
		in, out := &in.HTTP1IdleTimeout, &out.HTTP1IdleTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HTTP2WindowSize != nil {
		in, out := &in.HTTP2WindowSize, &out.HTTP2WindowSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2ConnectionWindowSize != nil {
		in, out := &in.HTTP2ConnectionWindowSize, &out.HTTP2ConnectionWindowSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2FrameSize != nil {
		in, out := &in.HTTP2FrameSize, &out.HTTP2FrameSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2KeepaliveInterval != nil {
		in, out := &in.HTTP2KeepaliveInterval, &out.HTTP2KeepaliveInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HTTP2KeepaliveTimeout != nil {
		in, out := &in.HTTP2KeepaliveTimeout, &out.HTTP2KeepaliveTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendHTTP.
func (in *FrontendHTTP) DeepCopy() *FrontendHTTP {
	if in == nil {
		return nil
	}
	out := new(FrontendHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendTCP) DeepCopyInto(out *FrontendTCP) {
	*out = *in
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(Keepalive)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendTCP.
func (in *FrontendTCP) DeepCopy() *FrontendTCP {
	if in == nil {
		return nil
	}
	out := new(FrontendTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendTLS) DeepCopyInto(out *FrontendTLS) {
	*out = *in
	if in.HandshakeTimeout != nil {
		in, out := &in.HandshakeTimeout, &out.HandshakeTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AlpnProtocols != nil {
		in, out := &in.AlpnProtocols, &out.AlpnProtocols
		*out = new([]TinyString)
		if **in != nil {
			in, out := *in, *out
			*out = make([]TinyString, len(*in))
			copy(*out, *in)
		}
	}
	if in.MinTLSVersion != nil {
		in, out := &in.MinTLSVersion, &out.MinTLSVersion
		*out = new(TLSVersion)
		**out = **in
	}
	if in.MaxTLSVersion != nil {
		in, out := &in.MaxTLSVersion, &out.MaxTLSVersion
		*out = new(TLSVersion)
		**out = **in
	}
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]CipherSuite, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendTLS.
func (in *FrontendTLS) DeepCopy() *FrontendTLS {
	if in == nil {
		return nil
	}
	out := new(FrontendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpAuth) DeepCopyInto(out *GcpAuth) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(GcpAuthType)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpAuth.
func (in *GcpAuth) DeepCopy() *GcpAuth {
	if in == nil {
		return nil
	}
	out := new(GcpAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiConfig) DeepCopyInto(out *GeminiConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiConfig.
func (in *GeminiConfig) DeepCopy() *GeminiConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimit) DeepCopyInto(out *GlobalRateLimit) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.Descriptors != nil {
		in, out := &in.Descriptors, &out.Descriptors
		*out = make([]RateLimitDescriptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimit.
func (in *GlobalRateLimit) DeepCopy() *GlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderTransformation) DeepCopyInto(out *HeaderTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderTransformation.
func (in *HeaderTransformation) DeepCopy() *HeaderTransformation {
	if in == nil {
		return nil
	}
	out := new(HeaderTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostnameRewrite) DeepCopyInto(out *HostnameRewrite) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostnameRewrite.
func (in *HostnameRewrite) DeepCopy() *HostnameRewrite {
	if in == nil {
		return nil
	}
	out := new(HostnameRewrite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.Digest != nil {
		in, out := &in.Digest, &out.Digest
		*out = new(string)
		**out = **in
	}
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSpec) DeepCopyInto(out *IstioSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSpec.
func (in *IstioSpec) DeepCopy() *IstioSpec {
	if in == nil {
		return nil
	}
	out := new(IstioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKS) DeepCopyInto(out *JWKS) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(RemoteJWKS)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKS.
func (in *JWKS) DeepCopy() *JWKS {
	if in == nil {
		return nil
	}
	out := new(JWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTAuthentication) DeepCopyInto(out *JWTAuthentication) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]JWTProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTAuthentication.
func (in *JWTAuthentication) DeepCopy() *JWTAuthentication {
	if in == nil {
		return nil
	}
	out := new(JWTAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTProvider) DeepCopyInto(out *JWTProvider) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.JWKS.DeepCopyInto(&out.JWKS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTProvider.
func (in *JWTProvider) DeepCopy() *JWTProvider {
	if in == nil {
		return nil
	}
	out := new(JWTProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Keepalive) DeepCopyInto(out *Keepalive) {
	*out = *in
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Keepalive.
func (in *Keepalive) DeepCopy() *Keepalive {
	if in == nil {
		return nil
	}
	out := new(Keepalive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProvider) DeepCopyInto(out *LLMProvider) {
	*out = *in
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureOpenAI != nil {
		in, out := &in.AzureOpenAI, &out.AzureOpenAI
		*out = new(AzureOpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gemini != nil {
		in, out := &in.Gemini, &out.Gemini
		*out = new(GeminiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VertexAI != nil {
		in, out := &in.VertexAI, &out.VertexAI
		*out = new(VertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProvider.
func (in *LLMProvider) DeepCopy() *LLMProvider {
	if in == nil {
		return nil
	}
	out := new(LLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalRateLimit) DeepCopyInto(out *LocalRateLimit) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(int32)
		**out = **in
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(int32)
		**out = **in
	}
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalRateLimit.
func (in *LocalRateLimit) DeepCopy() *LocalRateLimit {
	if in == nil {
		return nil
	}
	out := new(LocalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogTracingAttributes) DeepCopyInto(out *LogTracingAttributes) {
	*out = *in
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]TinyString, len(*in))
		copy(*out, *in)
	}
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]AttributeAdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogTracingAttributes.
func (in *LogTracingAttributes) DeepCopy() *LogTracingAttributes {
	if in == nil {
		return nil
	}
	out := new(LogTracingAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAuthentication) DeepCopyInto(out *MCPAuthentication) {
	*out = *in
	if in.ResourceMetadata != nil {
		in, out := &in.ResourceMetadata, &out.ResourceMetadata
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.McpIDP != nil {
		in, out := &in.McpIDP, &out.McpIDP
		*out = new(McpIDP)
		**out = **in
	}
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.JWKS.DeepCopyInto(&out.JWKS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAuthentication.
func (in *MCPAuthentication) DeepCopy() *MCPAuthentication {
	if in == nil {
		return nil
	}
	out := new(MCPAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPBackend) DeepCopyInto(out *MCPBackend) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]McpTargetSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPBackend.
func (in *MCPBackend) DeepCopy() *MCPBackend {
	if in == nil {
		return nil
	}
	out := new(MCPBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpSelector) DeepCopyInto(out *McpSelector) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpSelector.
func (in *McpSelector) DeepCopy() *McpSelector {
	if in == nil {
		return nil
	}
	out := new(McpSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpTarget) DeepCopyInto(out *McpTarget) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(LongString)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(MCPProtocol)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(BackendWithMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpTarget.
func (in *McpTarget) DeepCopy() *McpTarget {
	if in == nil {
		return nil
	}
	out := new(McpTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpTargetSelector) DeepCopyInto(out *McpTargetSelector) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(McpSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(McpTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpTargetSelector.
func (in *McpTargetSelector) DeepCopy() *McpTargetSelector {
	if in == nil {
		return nil
	}
	out := new(McpTargetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Message) DeepCopyInto(out *Message) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Message.
func (in *Message) DeepCopy() *Message {
	if in == nil {
		return nil
	}
	out := new(Message)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedLLMProvider) DeepCopyInto(out *NamedLLMProvider) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(BackendWithAI)
		(*in).DeepCopyInto(*out)
	}
	in.LLMProvider.DeepCopyInto(&out.LLMProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedLLMProvider.
func (in *NamedLLMProvider) DeepCopy() *NamedLLMProvider {
	if in == nil {
		return nil
	}
	out := new(NamedLLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIConfig) DeepCopyInto(out *OpenAIConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIConfig.
func (in *OpenAIConfig) DeepCopy() *OpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIModeration) DeepCopyInto(out *OpenAIModeration) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(BackendSimple)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModeration.
func (in *OpenAIModeration) DeepCopy() *OpenAIModeration {
	if in == nil {
		return nil
	}
	out := new(OpenAIModeration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityGroup) DeepCopyInto(out *PriorityGroup) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]NamedLLMProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityGroup.
func (in *PriorityGroup) DeepCopy() *PriorityGroup {
	if in == nil {
		return nil
	}
	out := new(PriorityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptCachingConfig) DeepCopyInto(out *PromptCachingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptCachingConfig.
func (in *PromptCachingConfig) DeepCopy() *PromptCachingConfig {
	if in == nil {
		return nil
	}
	out := new(PromptCachingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptguardRequest) DeepCopyInto(out *PromptguardRequest) {
	*out = *in
	if in.CustomResponse != nil {
		in, out := &in.CustomResponse, &out.CustomResponse
		*out = new(CustomResponse)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(Regex)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(Webhook)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenAIModeration != nil {
		in, out := &in.OpenAIModeration, &out.OpenAIModeration
		*out = new(OpenAIModeration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptguardRequest.
func (in *PromptguardRequest) DeepCopy() *PromptguardRequest {
	if in == nil {
		return nil
	}
	out := new(PromptguardRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptguardResponse) DeepCopyInto(out *PromptguardResponse) {
	*out = *in
	if in.CustomResponse != nil {
		in, out := &in.CustomResponse, &out.CustomResponse
		*out = new(CustomResponse)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(Regex)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(Webhook)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptguardResponse.
func (in *PromptguardResponse) DeepCopy() *PromptguardResponse {
	if in == nil {
		return nil
	}
	out := new(PromptguardResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitDescriptor) DeepCopyInto(out *RateLimitDescriptor) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]RateLimitDescriptorEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(RateLimitUnit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitDescriptor.
func (in *RateLimitDescriptor) DeepCopy() *RateLimitDescriptor {
	if in == nil {
		return nil
	}
	out := new(RateLimitDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitDescriptorEntry) DeepCopyInto(out *RateLimitDescriptorEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitDescriptorEntry.
func (in *RateLimitDescriptorEntry) DeepCopy() *RateLimitDescriptorEntry {
	if in == nil {
		return nil
	}
	out := new(RateLimitDescriptorEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimits) DeepCopyInto(out *RateLimits) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = make([]LocalRateLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalRateLimit)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimits.
func (in *RateLimits) DeepCopy() *RateLimits {
	if in == nil {
		return nil
	}
	out := new(RateLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Regex) DeepCopyInto(out *Regex) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]LongString, len(*in))
		copy(*out, *in)
	}
	if in.Builtins != nil {
		in, out := &in.Builtins, &out.Builtins
		*out = make([]BuiltIn, len(*in))
		copy(*out, *in)
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(Action)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Regex.
func (in *Regex) DeepCopy() *Regex {
	if in == nil {
		return nil
	}
	out := new(Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteJWKS) DeepCopyInto(out *RemoteJWKS) {
	*out = *in
	if in.CacheDuration != nil {
		in, out := &in.CacheDuration, &out.CacheDuration
		*out = new(v1.Duration)
		**out = **in
	}
	in.BackendRef.DeepCopyInto(&out.BackendRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteJWKS.
func (in *RemoteJWKS) DeepCopy() *RemoteJWKS {
	if in == nil {
		return nil
	}
	out := new(RemoteJWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAdd) DeepCopyInto(out *ResourceAdd) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAdd.
func (in *ResourceAdd) DeepCopy() *ResourceAdd {
	if in == nil {
		return nil
	}
	out := new(ResourceAdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Retry) DeepCopyInto(out *Retry) {
	*out = *in
	if in.HTTPRouteRetry != nil {
		in, out := &in.HTTPRouteRetry, &out.HTTPRouteRetry
		*out = new(apisv1.HTTPRouteRetry)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Retry.
func (in *Retry) DeepCopy() *Retry {
	if in == nil {
		return nil
	}
	out := new(Retry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelector) DeepCopyInto(out *SecretSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelector.
func (in *SecretSelector) DeepCopy() *SecretSelector {
	if in == nil {
		return nil
	}
	out := new(SecretSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShutdownSpec) DeepCopyInto(out *ShutdownSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShutdownSpec.
func (in *ShutdownSpec) DeepCopy() *ShutdownSpec {
	if in == nil {
		return nil
	}
	out := new(ShutdownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticBackend) DeepCopyInto(out *StaticBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticBackend.
func (in *StaticBackend) DeepCopy() *StaticBackend {
	if in == nil {
		return nil
	}
	out := new(StaticBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timeouts) DeepCopyInto(out *Timeouts) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timeouts.
func (in *Timeouts) DeepCopy() *Timeouts {
	if in == nil {
		return nil
	}
	out := new(Timeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(LogTracingAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceAdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RandomSampling != nil {
		in, out := &in.RandomSampling, &out.RandomSampling
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.ClientSampling != nil {
		in, out := &in.ClientSampling, &out.ClientSampling
		*out = new(shared.CELExpression)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tracing.
func (in *Tracing) DeepCopy() *Tracing {
	if in == nil {
		return nil
	}
	out := new(Tracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Traffic) DeepCopyInto(out *Traffic) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(PolicyPhase)
		**out = **in
	}
	if in.Transformation != nil {
		in, out := &in.Transformation, &out.Transformation
		*out = new(Transformation)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtProc != nil {
		in, out := &in.ExtProc, &out.ExtProc
		*out = new(ExtProc)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtAuth != nil {
		in, out := &in.ExtAuth, &out.ExtAuth
		*out = new(ExtAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(CORS)
		(*in).DeepCopyInto(*out)
	}
	if in.Csrf != nil {
		in, out := &in.Csrf, &out.Csrf
		*out = new(CSRF)
		(*in).DeepCopyInto(*out)
	}
	if in.HeaderModifiers != nil {
		in, out := &in.HeaderModifiers, &out.HeaderModifiers
		*out = new(shared.HeaderModifiers)
		(*in).DeepCopyInto(*out)
	}
	if in.HostnameRewrite != nil {
		in, out := &in.HostnameRewrite, &out.HostnameRewrite
		*out = new(HostnameRewrite)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(Timeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(Retry)
		(*in).DeepCopyInto(*out)
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(shared.Authorization)
		(*in).DeepCopyInto(*out)
	}
	if in.JWTAuthentication != nil {
		in, out := &in.JWTAuthentication, &out.JWTAuthentication
		*out = new(JWTAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuthentication != nil {
		in, out := &in.BasicAuthentication, &out.BasicAuthentication
		*out = new(BasicAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKeyAuthentication != nil {
		in, out := &in.APIKeyAuthentication, &out.APIKeyAuthentication
		*out = new(APIKeyAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.DirectResponse != nil {
		in, out := &in.DirectResponse, &out.DirectResponse
		*out = new(DirectResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Traffic.
func (in *Traffic) DeepCopy() *Traffic {
	if in == nil {
		return nil
	}
	out := new(Traffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transform) DeepCopyInto(out *Transform) {
	*out = *in
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]HeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]HeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]HeaderName, len(*in))
		copy(*out, *in)
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(shared.CELExpression)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transform.
func (in *Transform) DeepCopy() *Transform {
	if in == nil {
		return nil
	}
	out := new(Transform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transformation) DeepCopyInto(out *Transformation) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(Transform)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(Transform)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transformation.
func (in *Transformation) DeepCopy() *Transformation {
	if in == nil {
		return nil
	}
	out := new(Transformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexAIConfig) DeepCopyInto(out *VertexAIConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexAIConfig.
func (in *VertexAIConfig) DeepCopy() *VertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(VertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webhook) DeepCopyInto(out *Webhook) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.ForwardHeaderMatches != nil {
		in, out := &in.ForwardHeaderMatches, &out.ForwardHeaderMatches
		*out = make([]apisv1.HTTPHeaderMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webhook.
func (in *Webhook) DeepCopy() *Webhook {
	if in == nil {
		return nil
	}
	out := new(Webhook)
	in.DeepCopyInto(out)
	return out
}
