//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package agentgateway

import (
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/shared"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIBackend) DeepCopyInto(out *AIBackend) {
	*out = *in
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityGroups != nil {
		in, out := &in.PriorityGroups, &out.PriorityGroups
		*out = make([]PriorityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIBackend.
func (in *AIBackend) DeepCopy() *AIBackend {
	if in == nil {
		return nil
	}
	out := new(AIBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPromptEnrichment) DeepCopyInto(out *AIPromptEnrichment) {
	*out = *in
	if in.Prepend != nil {
		in, out := &in.Prepend, &out.Prepend
		*out = make([]Message, len(*in))
		copy(*out, *in)
	}
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = make([]Message, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPromptEnrichment.
func (in *AIPromptEnrichment) DeepCopy() *AIPromptEnrichment {
	if in == nil {
		return nil
	}
	out := new(AIPromptEnrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIPromptGuard) DeepCopyInto(out *AIPromptGuard) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = make([]PromptguardRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = make([]PromptguardResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIPromptGuard.
func (in *AIPromptGuard) DeepCopy() *AIPromptGuard {
	if in == nil {
		return nil
	}
	out := new(AIPromptGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSGuardrailConfig) DeepCopyInto(out *AWSGuardrailConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSGuardrailConfig.
func (in *AWSGuardrailConfig) DeepCopy() *AWSGuardrailConfig {
	if in == nil {
		return nil
	}
	out := new(AWSGuardrailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAPIKeyAuthentication) DeepCopyInto(out *AgentAPIKeyAuthentication) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.SecretSelector != nil {
		in, out := &in.SecretSelector, &out.SecretSelector
		*out = new(SecretSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAPIKeyAuthentication.
func (in *AgentAPIKeyAuthentication) DeepCopy() *AgentAPIKeyAuthentication {
	if in == nil {
		return nil
	}
	out := new(AgentAPIKeyAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAccessLog) DeepCopyInto(out *AgentAccessLog) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(AgentLogTracingFields)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAccessLog.
func (in *AgentAccessLog) DeepCopy() *AgentAccessLog {
	if in == nil {
		return nil
	}
	out := new(AgentAccessLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentAttributeAdd) DeepCopyInto(out *AgentAttributeAdd) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentAttributeAdd.
func (in *AgentAttributeAdd) DeepCopy() *AgentAttributeAdd {
	if in == nil {
		return nil
	}
	out := new(AgentAttributeAdd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentBasicAuthentication) DeepCopyInto(out *AgentBasicAuthentication) {
	*out = *in
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentBasicAuthentication.
func (in *AgentBasicAuthentication) DeepCopy() *AgentBasicAuthentication {
	if in == nil {
		return nil
	}
	out := new(AgentBasicAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCSRFPolicy) DeepCopyInto(out *AgentCSRFPolicy) {
	*out = *in
	if in.AdditionalOrigins != nil {
		in, out := &in.AdditionalOrigins, &out.AdditionalOrigins
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCSRFPolicy.
func (in *AgentCSRFPolicy) DeepCopy() *AgentCSRFPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentCSRFPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCorsPolicy) DeepCopyInto(out *AgentCorsPolicy) {
	*out = *in
	if in.HTTPCORSFilter != nil {
		in, out := &in.HTTPCORSFilter, &out.HTTPCORSFilter
		*out = new(apisv1.HTTPCORSFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCorsPolicy.
func (in *AgentCorsPolicy) DeepCopy() *AgentCorsPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentCorsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDynamicForwardProxyBackend) DeepCopyInto(out *AgentDynamicForwardProxyBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDynamicForwardProxyBackend.
func (in *AgentDynamicForwardProxyBackend) DeepCopy() *AgentDynamicForwardProxyBackend {
	if in == nil {
		return nil
	}
	out := new(AgentDynamicForwardProxyBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentExtAuthBody) DeepCopyInto(out *AgentExtAuthBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentExtAuthBody.
func (in *AgentExtAuthBody) DeepCopy() *AgentExtAuthBody {
	if in == nil {
		return nil
	}
	out := new(AgentExtAuthBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentExtAuthPolicy) DeepCopyInto(out *AgentExtAuthPolicy) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.ForwardBody != nil {
		in, out := &in.ForwardBody, &out.ForwardBody
		*out = new(AgentExtAuthBody)
		**out = **in
	}
	if in.ContextExtensions != nil {
		in, out := &in.ContextExtensions, &out.ContextExtensions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentExtAuthPolicy.
func (in *AgentExtAuthPolicy) DeepCopy() *AgentExtAuthPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentExtAuthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentExtProcPolicy) DeepCopyInto(out *AgentExtProcPolicy) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentExtProcPolicy.
func (in *AgentExtProcPolicy) DeepCopy() *AgentExtProcPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentExtProcPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHeaderTransformation) DeepCopyInto(out *AgentHeaderTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHeaderTransformation.
func (in *AgentHeaderTransformation) DeepCopy() *AgentHeaderTransformation {
	if in == nil {
		return nil
	}
	out := new(AgentHeaderTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHostnameRewriteConfig) DeepCopyInto(out *AgentHostnameRewriteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHostnameRewriteConfig.
func (in *AgentHostnameRewriteConfig) DeepCopy() *AgentHostnameRewriteConfig {
	if in == nil {
		return nil
	}
	out := new(AgentHostnameRewriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentJWKS) DeepCopyInto(out *AgentJWKS) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(AgentRemoteJWKS)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentJWKS.
func (in *AgentJWKS) DeepCopy() *AgentJWKS {
	if in == nil {
		return nil
	}
	out := new(AgentJWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentJWTAuthentication) DeepCopyInto(out *AgentJWTAuthentication) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]AgentJWTProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentJWTAuthentication.
func (in *AgentJWTAuthentication) DeepCopy() *AgentJWTAuthentication {
	if in == nil {
		return nil
	}
	out := new(AgentJWTAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentJWTProvider) DeepCopyInto(out *AgentJWTProvider) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.JWKS.DeepCopyInto(&out.JWKS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentJWTProvider.
func (in *AgentJWTProvider) DeepCopy() *AgentJWTProvider {
	if in == nil {
		return nil
	}
	out := new(AgentJWTProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLocalRateLimitPolicy) DeepCopyInto(out *AgentLocalRateLimitPolicy) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(int32)
		**out = **in
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(int32)
		**out = **in
	}
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLocalRateLimitPolicy.
func (in *AgentLocalRateLimitPolicy) DeepCopy() *AgentLocalRateLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentLocalRateLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLogTracingFields) DeepCopyInto(out *AgentLogTracingFields) {
	*out = *in
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]TinyString, len(*in))
		copy(*out, *in)
	}
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]AgentAttributeAdd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLogTracingFields.
func (in *AgentLogTracingFields) DeepCopy() *AgentLogTracingFields {
	if in == nil {
		return nil
	}
	out := new(AgentLogTracingFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimit) DeepCopyInto(out *AgentRateLimit) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = make([]AgentLocalRateLimitPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(AgentRateLimitPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimit.
func (in *AgentRateLimit) DeepCopy() *AgentRateLimit {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimitDescriptor) DeepCopyInto(out *AgentRateLimitDescriptor) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]AgentRateLimitDescriptorEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(RateLimitUnit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimitDescriptor.
func (in *AgentRateLimitDescriptor) DeepCopy() *AgentRateLimitDescriptor {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimitDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimitDescriptorEntry) DeepCopyInto(out *AgentRateLimitDescriptorEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimitDescriptorEntry.
func (in *AgentRateLimitDescriptorEntry) DeepCopy() *AgentRateLimitDescriptorEntry {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimitDescriptorEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimitPolicy) DeepCopyInto(out *AgentRateLimitPolicy) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.Descriptors != nil {
		in, out := &in.Descriptors, &out.Descriptors
		*out = make([]AgentRateLimitDescriptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimitPolicy.
func (in *AgentRateLimitPolicy) DeepCopy() *AgentRateLimitPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimitPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRemoteJWKS) DeepCopyInto(out *AgentRemoteJWKS) {
	*out = *in
	if in.CacheDuration != nil {
		in, out := &in.CacheDuration, &out.CacheDuration
		*out = new(v1.Duration)
		**out = **in
	}
	in.BackendRef.DeepCopyInto(&out.BackendRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRemoteJWKS.
func (in *AgentRemoteJWKS) DeepCopy() *AgentRemoteJWKS {
	if in == nil {
		return nil
	}
	out := new(AgentRemoteJWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRetry) DeepCopyInto(out *AgentRetry) {
	*out = *in
	if in.HTTPRouteRetry != nil {
		in, out := &in.HTTPRouteRetry, &out.HTTPRouteRetry
		*out = new(apisv1.HTTPRouteRetry)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRetry.
func (in *AgentRetry) DeepCopy() *AgentRetry {
	if in == nil {
		return nil
	}
	out := new(AgentRetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStaticBackend) DeepCopyInto(out *AgentStaticBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStaticBackend.
func (in *AgentStaticBackend) DeepCopy() *AgentStaticBackend {
	if in == nil {
		return nil
	}
	out := new(AgentStaticBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTimeouts) DeepCopyInto(out *AgentTimeouts) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTimeouts.
func (in *AgentTimeouts) DeepCopy() *AgentTimeouts {
	if in == nil {
		return nil
	}
	out := new(AgentTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTracing) DeepCopyInto(out *AgentTracing) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(AgentLogTracingFields)
		(*in).DeepCopyInto(*out)
	}
	if in.RandomSampling != nil {
		in, out := &in.RandomSampling, &out.RandomSampling
		*out = new(shared.CELExpression)
		**out = **in
	}
	if in.ClientSampling != nil {
		in, out := &in.ClientSampling, &out.ClientSampling
		*out = new(shared.CELExpression)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTracing.
func (in *AgentTracing) DeepCopy() *AgentTracing {
	if in == nil {
		return nil
	}
	out := new(AgentTracing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTransform) DeepCopyInto(out *AgentTransform) {
	*out = *in
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make([]AgentHeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]AgentHeaderTransformation, len(*in))
		copy(*out, *in)
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = make([]AgentHeaderName, len(*in))
		copy(*out, *in)
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(shared.CELExpression)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTransform.
func (in *AgentTransform) DeepCopy() *AgentTransform {
	if in == nil {
		return nil
	}
	out := new(AgentTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTransformationPolicy) DeepCopyInto(out *AgentTransformationPolicy) {
	*out = *in
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(AgentTransform)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(AgentTransform)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTransformationPolicy.
func (in *AgentTransformationPolicy) DeepCopy() *AgentTransformationPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentTransformationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackend) DeepCopyInto(out *AgentgatewayBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackend.
func (in *AgentgatewayBackend) DeepCopy() *AgentgatewayBackend {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendList) DeepCopyInto(out *AgentgatewayBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentgatewayBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendList.
func (in *AgentgatewayBackendList) DeepCopy() *AgentgatewayBackendList {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendSpec) DeepCopyInto(out *AgentgatewayBackendSpec) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(AgentStaticBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(AIBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.DynamicForwardProxy != nil {
		in, out := &in.DynamicForwardProxy, &out.DynamicForwardProxy
		*out = new(AgentDynamicForwardProxyBackend)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(AgentgatewayPolicyBackendFull)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendSpec.
func (in *AgentgatewayBackendSpec) DeepCopy() *AgentgatewayBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayBackendStatus) DeepCopyInto(out *AgentgatewayBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayBackendStatus.
func (in *AgentgatewayBackendStatus) DeepCopy() *AgentgatewayBackendStatus {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayKeepalive) DeepCopyInto(out *AgentgatewayKeepalive) {
	*out = *in
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(int32)
		**out = **in
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayKeepalive.
func (in *AgentgatewayKeepalive) DeepCopy() *AgentgatewayKeepalive {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayKeepalive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicy) DeepCopyInto(out *AgentgatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicy.
func (in *AgentgatewayPolicy) DeepCopy() *AgentgatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyBackendAI) DeepCopyInto(out *AgentgatewayPolicyBackendAI) {
	*out = *in
	in.AgentgatewayPolicyBackendSimple.DeepCopyInto(&out.AgentgatewayPolicyBackendSimple)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(BackendAI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyBackendAI.
func (in *AgentgatewayPolicyBackendAI) DeepCopy() *AgentgatewayPolicyBackendAI {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyBackendAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyBackendFull) DeepCopyInto(out *AgentgatewayPolicyBackendFull) {
	*out = *in
	in.AgentgatewayPolicyBackendSimple.DeepCopyInto(&out.AgentgatewayPolicyBackendSimple)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(BackendAI)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(BackendMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyBackendFull.
func (in *AgentgatewayPolicyBackendFull) DeepCopy() *AgentgatewayPolicyBackendFull {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyBackendFull)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyBackendMCP) DeepCopyInto(out *AgentgatewayPolicyBackendMCP) {
	*out = *in
	in.AgentgatewayPolicyBackendSimple.DeepCopyInto(&out.AgentgatewayPolicyBackendSimple)
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(BackendMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyBackendMCP.
func (in *AgentgatewayPolicyBackendMCP) DeepCopy() *AgentgatewayPolicyBackendMCP {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyBackendMCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyBackendSimple) DeepCopyInto(out *AgentgatewayPolicyBackendSimple) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(BackendTCP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(BackendTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(BackendHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(BackendAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyBackendSimple.
func (in *AgentgatewayPolicyBackendSimple) DeepCopy() *AgentgatewayPolicyBackendSimple {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyBackendSimple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyFrontend) DeepCopyInto(out *AgentgatewayPolicyFrontend) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(FrontendTCP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(FrontendTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(FrontendHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = new(AgentAccessLog)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(AgentTracing)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyFrontend.
func (in *AgentgatewayPolicyFrontend) DeepCopy() *AgentgatewayPolicyFrontend {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyList) DeepCopyInto(out *AgentgatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentgatewayPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyList.
func (in *AgentgatewayPolicyList) DeepCopy() *AgentgatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentgatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicySpec) DeepCopyInto(out *AgentgatewayPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]shared.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetSelectors != nil {
		in, out := &in.TargetSelectors, &out.TargetSelectors
		*out = make([]shared.LocalPolicyTargetSelectorWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frontend != nil {
		in, out := &in.Frontend, &out.Frontend
		*out = new(AgentgatewayPolicyFrontend)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(AgentgatewayPolicyTraffic)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(AgentgatewayPolicyBackendFull)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicySpec.
func (in *AgentgatewayPolicySpec) DeepCopy() *AgentgatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayPolicyTraffic) DeepCopyInto(out *AgentgatewayPolicyTraffic) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(PolicyPhase)
		**out = **in
	}
	if in.Transformation != nil {
		in, out := &in.Transformation, &out.Transformation
		*out = new(AgentTransformationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtProc != nil {
		in, out := &in.ExtProc, &out.ExtProc
		*out = new(AgentExtProcPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtAuth != nil {
		in, out := &in.ExtAuth, &out.ExtAuth
		*out = new(AgentExtAuthPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(AgentRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(AgentCorsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Csrf != nil {
		in, out := &in.Csrf, &out.Csrf
		*out = new(AgentCSRFPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.HeaderModifiers != nil {
		in, out := &in.HeaderModifiers, &out.HeaderModifiers
		*out = new(shared.HeaderModifiers)
		(*in).DeepCopyInto(*out)
	}
	if in.HostnameRewrite != nil {
		in, out := &in.HostnameRewrite, &out.HostnameRewrite
		*out = new(AgentHostnameRewriteConfig)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(AgentTimeouts)
		(*in).DeepCopyInto(*out)
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(shared.Retry)
		(*in).DeepCopyInto(*out)
	}
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(shared.Authorization)
		(*in).DeepCopyInto(*out)
	}
	if in.JWTAuthentication != nil {
		in, out := &in.JWTAuthentication, &out.JWTAuthentication
		*out = new(AgentJWTAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuthentication != nil {
		in, out := &in.BasicAuthentication, &out.BasicAuthentication
		*out = new(AgentBasicAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKeyAuthentication != nil {
		in, out := &in.APIKeyAuthentication, &out.APIKeyAuthentication
		*out = new(AgentAPIKeyAuthentication)
		(*in).DeepCopyInto(*out)
	}
	if in.DirectResponse != nil {
		in, out := &in.DirectResponse, &out.DirectResponse
		*out = new(DirectResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayPolicyTraffic.
func (in *AgentgatewayPolicyTraffic) DeepCopy() *AgentgatewayPolicyTraffic {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayPolicyTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicConfig) DeepCopyInto(out *AnthropicConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicConfig.
func (in *AnthropicConfig) DeepCopy() *AnthropicConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOpenAIConfig) DeepCopyInto(out *AzureOpenAIConfig) {
	*out = *in
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(ShortString)
		**out = **in
	}
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(TinyString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOpenAIConfig.
func (in *AzureOpenAIConfig) DeepCopy() *AzureOpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(AzureOpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAI) DeepCopyInto(out *BackendAI) {
	*out = *in
	if in.PromptEnrichment != nil {
		in, out := &in.PromptEnrichment, &out.PromptEnrichment
		*out = new(AIPromptEnrichment)
		(*in).DeepCopyInto(*out)
	}
	if in.PromptGuard != nil {
		in, out := &in.PromptGuard, &out.PromptGuard
		*out = new(AIPromptGuard)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]FieldDefault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]FieldDefault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelAliases != nil {
		in, out := &in.ModelAliases, &out.ModelAliases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PromptCaching != nil {
		in, out := &in.PromptCaching, &out.PromptCaching
		*out = new(PromptCachingConfig)
		**out = **in
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(map[string]RouteType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAI.
func (in *BackendAI) DeepCopy() *BackendAI {
	if in == nil {
		return nil
	}
	out := new(BackendAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAuth) DeepCopyInto(out *BackendAuth) {
	*out = *in
	if in.InlineKey != nil {
		in, out := &in.InlineKey, &out.InlineKey
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Passthrough != nil {
		in, out := &in.Passthrough, &out.Passthrough
		*out = new(BackendAuthPassthrough)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAuth.
func (in *BackendAuth) DeepCopy() *BackendAuth {
	if in == nil {
		return nil
	}
	out := new(BackendAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendAuthPassthrough) DeepCopyInto(out *BackendAuthPassthrough) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendAuthPassthrough.
func (in *BackendAuthPassthrough) DeepCopy() *BackendAuthPassthrough {
	if in == nil {
		return nil
	}
	out := new(BackendAuthPassthrough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendHTTP) DeepCopyInto(out *BackendHTTP) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(HTTPVersion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendHTTP.
func (in *BackendHTTP) DeepCopy() *BackendHTTP {
	if in == nil {
		return nil
	}
	out := new(BackendHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendMCP) DeepCopyInto(out *BackendMCP) {
	*out = *in
	if in.Authorization != nil {
		in, out := &in.Authorization, &out.Authorization
		*out = new(shared.Authorization)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(MCPAuthentication)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendMCP.
func (in *BackendMCP) DeepCopy() *BackendMCP {
	if in == nil {
		return nil
	}
	out := new(BackendMCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTCP) DeepCopyInto(out *BackendTCP) {
	*out = *in
	if in.Keepalive != nil {
		in, out := &in.Keepalive, &out.Keepalive
		*out = new(AgentgatewayKeepalive)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTCP.
func (in *BackendTCP) DeepCopy() *BackendTCP {
	if in == nil {
		return nil
	}
	out := new(BackendTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendTLS) DeepCopyInto(out *BackendTLS) {
	*out = *in
	if in.MtlsCertificateRef != nil {
		in, out := &in.MtlsCertificateRef, &out.MtlsCertificateRef
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CACertificateRefs != nil {
		in, out := &in.CACertificateRefs, &out.CACertificateRefs
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(InsecureTLSMode)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(SNI)
		**out = **in
	}
	if in.VerifySubjectAltNames != nil {
		in, out := &in.VerifySubjectAltNames, &out.VerifySubjectAltNames
		*out = make([]ShortString, len(*in))
		copy(*out, *in)
	}
	if in.AlpnProtocols != nil {
		in, out := &in.AlpnProtocols, &out.AlpnProtocols
		*out = new([]TinyString)
		if **in != nil {
			in, out := *in, *out
			*out = make([]TinyString, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendTLS.
func (in *BackendTLS) DeepCopy() *BackendTLS {
	if in == nil {
		return nil
	}
	out := new(BackendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockConfig) DeepCopyInto(out *BedrockConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
	if in.Guardrail != nil {
		in, out := &in.Guardrail, &out.Guardrail
		*out = new(AWSGuardrailConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockConfig.
func (in *BedrockConfig) DeepCopy() *BedrockConfig {
	if in == nil {
		return nil
	}
	out := new(BedrockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResponse) DeepCopyInto(out *CustomResponse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResponse.
func (in *CustomResponse) DeepCopy() *CustomResponse {
	if in == nil {
		return nil
	}
	out := new(CustomResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectResponse) DeepCopyInto(out *DirectResponse) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectResponse.
func (in *DirectResponse) DeepCopy() *DirectResponse {
	if in == nil {
		return nil
	}
	out := new(DirectResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldDefault) DeepCopyInto(out *FieldDefault) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldDefault.
func (in *FieldDefault) DeepCopy() *FieldDefault {
	if in == nil {
		return nil
	}
	out := new(FieldDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendHTTP) DeepCopyInto(out *FrontendHTTP) {
	*out = *in
	if in.MaxBufferSize != nil {
		in, out := &in.MaxBufferSize, &out.MaxBufferSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP1MaxHeaders != nil {
		in, out := &in.HTTP1MaxHeaders, &out.HTTP1MaxHeaders
		*out = new(int32)
		**out = **in
	}
	if in.HTTP1IdleTimeout != nil {
		in, out := &in.HTTP1IdleTimeout, &out.HTTP1IdleTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HTTP2WindowSize != nil {
		in, out := &in.HTTP2WindowSize, &out.HTTP2WindowSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2ConnectionWindowSize != nil {
		in, out := &in.HTTP2ConnectionWindowSize, &out.HTTP2ConnectionWindowSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2FrameSize != nil {
		in, out := &in.HTTP2FrameSize, &out.HTTP2FrameSize
		*out = new(int32)
		**out = **in
	}
	if in.HTTP2KeepaliveInterval != nil {
		in, out := &in.HTTP2KeepaliveInterval, &out.HTTP2KeepaliveInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HTTP2KeepaliveTimeout != nil {
		in, out := &in.HTTP2KeepaliveTimeout, &out.HTTP2KeepaliveTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendHTTP.
func (in *FrontendHTTP) DeepCopy() *FrontendHTTP {
	if in == nil {
		return nil
	}
	out := new(FrontendHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendTCP) DeepCopyInto(out *FrontendTCP) {
	*out = *in
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(AgentgatewayKeepalive)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendTCP.
func (in *FrontendTCP) DeepCopy() *FrontendTCP {
	if in == nil {
		return nil
	}
	out := new(FrontendTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendTLS) DeepCopyInto(out *FrontendTLS) {
	*out = *in
	if in.HandshakeTimeout != nil {
		in, out := &in.HandshakeTimeout, &out.HandshakeTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AlpnProtocols != nil {
		in, out := &in.AlpnProtocols, &out.AlpnProtocols
		*out = new([]TinyString)
		if **in != nil {
			in, out := *in, *out
			*out = make([]TinyString, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendTLS.
func (in *FrontendTLS) DeepCopy() *FrontendTLS {
	if in == nil {
		return nil
	}
	out := new(FrontendTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiConfig) DeepCopyInto(out *GeminiConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiConfig.
func (in *GeminiConfig) DeepCopy() *GeminiConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProvider) DeepCopyInto(out *LLMProvider) {
	*out = *in
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureOpenAI != nil {
		in, out := &in.AzureOpenAI, &out.AzureOpenAI
		*out = new(AzureOpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gemini != nil {
		in, out := &in.Gemini, &out.Gemini
		*out = new(GeminiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VertexAI != nil {
		in, out := &in.VertexAI, &out.VertexAI
		*out = new(VertexAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = new(BedrockConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProvider.
func (in *LLMProvider) DeepCopy() *LLMProvider {
	if in == nil {
		return nil
	}
	out := new(LLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPAuthentication) DeepCopyInto(out *MCPAuthentication) {
	*out = *in
	if in.ResourceMetadata != nil {
		in, out := &in.ResourceMetadata, &out.ResourceMetadata
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.McpIDP != nil {
		in, out := &in.McpIDP, &out.McpIDP
		*out = new(McpIDP)
		**out = **in
	}
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.JWKS.DeepCopyInto(&out.JWKS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPAuthentication.
func (in *MCPAuthentication) DeepCopy() *MCPAuthentication {
	if in == nil {
		return nil
	}
	out := new(MCPAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPBackend) DeepCopyInto(out *MCPBackend) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]McpTargetSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPBackend.
func (in *MCPBackend) DeepCopy() *MCPBackend {
	if in == nil {
		return nil
	}
	out := new(MCPBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpSelector) DeepCopyInto(out *McpSelector) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpSelector.
func (in *McpSelector) DeepCopy() *McpSelector {
	if in == nil {
		return nil
	}
	out := new(McpSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpTarget) DeepCopyInto(out *McpTarget) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(LongString)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(MCPProtocol)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(AgentgatewayPolicyBackendMCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpTarget.
func (in *McpTarget) DeepCopy() *McpTarget {
	if in == nil {
		return nil
	}
	out := new(McpTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *McpTargetSelector) DeepCopyInto(out *McpTargetSelector) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(McpSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(McpTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new McpTargetSelector.
func (in *McpTargetSelector) DeepCopy() *McpTargetSelector {
	if in == nil {
		return nil
	}
	out := new(McpTargetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Message) DeepCopyInto(out *Message) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Message.
func (in *Message) DeepCopy() *Message {
	if in == nil {
		return nil
	}
	out := new(Message)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedLLMProvider) DeepCopyInto(out *NamedLLMProvider) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(AgentgatewayPolicyBackendAI)
		(*in).DeepCopyInto(*out)
	}
	in.LLMProvider.DeepCopyInto(&out.LLMProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedLLMProvider.
func (in *NamedLLMProvider) DeepCopy() *NamedLLMProvider {
	if in == nil {
		return nil
	}
	out := new(NamedLLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIConfig) DeepCopyInto(out *OpenAIConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIConfig.
func (in *OpenAIConfig) DeepCopy() *OpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIModeration) DeepCopyInto(out *OpenAIModeration) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new(AgentgatewayPolicyBackendSimple)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIModeration.
func (in *OpenAIModeration) DeepCopy() *OpenAIModeration {
	if in == nil {
		return nil
	}
	out := new(OpenAIModeration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityGroup) DeepCopyInto(out *PriorityGroup) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]NamedLLMProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityGroup.
func (in *PriorityGroup) DeepCopy() *PriorityGroup {
	if in == nil {
		return nil
	}
	out := new(PriorityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptCachingConfig) DeepCopyInto(out *PromptCachingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptCachingConfig.
func (in *PromptCachingConfig) DeepCopy() *PromptCachingConfig {
	if in == nil {
		return nil
	}
	out := new(PromptCachingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptguardRequest) DeepCopyInto(out *PromptguardRequest) {
	*out = *in
	if in.CustomResponse != nil {
		in, out := &in.CustomResponse, &out.CustomResponse
		*out = new(CustomResponse)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(Regex)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(Webhook)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenAIModeration != nil {
		in, out := &in.OpenAIModeration, &out.OpenAIModeration
		*out = new(OpenAIModeration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptguardRequest.
func (in *PromptguardRequest) DeepCopy() *PromptguardRequest {
	if in == nil {
		return nil
	}
	out := new(PromptguardRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptguardResponse) DeepCopyInto(out *PromptguardResponse) {
	*out = *in
	if in.CustomResponse != nil {
		in, out := &in.CustomResponse, &out.CustomResponse
		*out = new(CustomResponse)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(Regex)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(Webhook)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptguardResponse.
func (in *PromptguardResponse) DeepCopy() *PromptguardResponse {
	if in == nil {
		return nil
	}
	out := new(PromptguardResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Regex) DeepCopyInto(out *Regex) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]LongString, len(*in))
		copy(*out, *in)
	}
	if in.Builtins != nil {
		in, out := &in.Builtins, &out.Builtins
		*out = make([]BuiltIn, len(*in))
		copy(*out, *in)
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(Action)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Regex.
func (in *Regex) DeepCopy() *Regex {
	if in == nil {
		return nil
	}
	out := new(Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelector) DeepCopyInto(out *SecretSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelector.
func (in *SecretSelector) DeepCopy() *SecretSelector {
	if in == nil {
		return nil
	}
	out := new(SecretSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexAIConfig) DeepCopyInto(out *VertexAIConfig) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ShortString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexAIConfig.
func (in *VertexAIConfig) DeepCopy() *VertexAIConfig {
	if in == nil {
		return nil
	}
	out := new(VertexAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webhook) DeepCopyInto(out *Webhook) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.ForwardHeaderMatches != nil {
		in, out := &in.ForwardHeaderMatches, &out.ForwardHeaderMatches
		*out = make([]apisv1.HTTPHeaderMatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webhook.
func (in *Webhook) DeepCopy() *Webhook {
	if in == nil {
		return nil
	}
	out := new(Webhook)
	in.DeepCopyInto(out)
	return out
}
