// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeDirectResponses implements DirectResponseInterface
type fakeDirectResponses struct {
	*gentype.FakeClientWithList[*kgateway.DirectResponse, *kgateway.DirectResponseList]
	Fake *FakeGatewayKgateway
}

func newFakeDirectResponses(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.DirectResponseInterface {
	return &fakeDirectResponses{
		gentype.NewFakeClientWithList[*kgateway.DirectResponse, *kgateway.DirectResponseList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("directresponses"),
			kgateway.SchemeGroupVersion.WithKind("DirectResponse"),
			func() *kgateway.DirectResponse { return &kgateway.DirectResponse{} },
			func() *kgateway.DirectResponseList { return &kgateway.DirectResponseList{} },
			func(dst, src *kgateway.DirectResponseList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.DirectResponseList) []*kgateway.DirectResponse {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.DirectResponseList, items []*kgateway.DirectResponse) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
