// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGatewayKgateway struct {
	*testing.Fake
}

func (c *FakeGatewayKgateway) Backends(namespace string) kgateway.BackendInterface {
	return newFakeBackends(c, namespace)
}

func (c *FakeGatewayKgateway) BackendConfigPolicies(namespace string) kgateway.BackendConfigPolicyInterface {
	return newFakeBackendConfigPolicies(c, namespace)
}

func (c *FakeGatewayKgateway) DirectResponses(namespace string) kgateway.DirectResponseInterface {
	return newFakeDirectResponses(c, namespace)
}

func (c *FakeGatewayKgateway) GatewayExtensions(namespace string) kgateway.GatewayExtensionInterface {
	return newFakeGatewayExtensions(c, namespace)
}

func (c *FakeGatewayKgateway) GatewayParameters(namespace string) kgateway.GatewayParametersInterface {
	return newFakeGatewayParameters(c, namespace)
}

func (c *FakeGatewayKgateway) HTTPListenerPolicies(namespace string) kgateway.HTTPListenerPolicyInterface {
	return newFakeHTTPListenerPolicies(c, namespace)
}

func (c *FakeGatewayKgateway) ListenerPolicies(namespace string) kgateway.ListenerPolicyInterface {
	return newFakeListenerPolicies(c, namespace)
}

func (c *FakeGatewayKgateway) TrafficPolicies(namespace string) kgateway.TrafficPolicyInterface {
	return newFakeTrafficPolicies(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGatewayKgateway) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
