// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeTrafficPolicies implements TrafficPolicyInterface
type fakeTrafficPolicies struct {
	*gentype.FakeClientWithList[*kgateway.TrafficPolicy, *kgateway.TrafficPolicyList]
	Fake *FakeGatewayKgateway
}

func newFakeTrafficPolicies(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.TrafficPolicyInterface {
	return &fakeTrafficPolicies{
		gentype.NewFakeClientWithList[*kgateway.TrafficPolicy, *kgateway.TrafficPolicyList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("trafficpolicies"),
			kgateway.SchemeGroupVersion.WithKind("TrafficPolicy"),
			func() *kgateway.TrafficPolicy { return &kgateway.TrafficPolicy{} },
			func() *kgateway.TrafficPolicyList { return &kgateway.TrafficPolicyList{} },
			func(dst, src *kgateway.TrafficPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.TrafficPolicyList) []*kgateway.TrafficPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.TrafficPolicyList, items []*kgateway.TrafficPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
