// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeGatewayParameters implements GatewayParametersInterface
type fakeGatewayParameters struct {
	*gentype.FakeClientWithList[*kgateway.GatewayParameters, *kgateway.GatewayParametersList]
	Fake *FakeGatewayKgateway
}

func newFakeGatewayParameters(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.GatewayParametersInterface {
	return &fakeGatewayParameters{
		gentype.NewFakeClientWithList[*kgateway.GatewayParameters, *kgateway.GatewayParametersList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("gatewayparameters"),
			kgateway.SchemeGroupVersion.WithKind("GatewayParameters"),
			func() *kgateway.GatewayParameters { return &kgateway.GatewayParameters{} },
			func() *kgateway.GatewayParametersList { return &kgateway.GatewayParametersList{} },
			func(dst, src *kgateway.GatewayParametersList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.GatewayParametersList) []*kgateway.GatewayParameters {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.GatewayParametersList, items []*kgateway.GatewayParameters) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
