// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeGatewayExtensions implements GatewayExtensionInterface
type fakeGatewayExtensions struct {
	*gentype.FakeClientWithList[*kgateway.GatewayExtension, *kgateway.GatewayExtensionList]
	Fake *FakeGatewayKgateway
}

func newFakeGatewayExtensions(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.GatewayExtensionInterface {
	return &fakeGatewayExtensions{
		gentype.NewFakeClientWithList[*kgateway.GatewayExtension, *kgateway.GatewayExtensionList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("gatewayextensions"),
			kgateway.SchemeGroupVersion.WithKind("GatewayExtension"),
			func() *kgateway.GatewayExtension { return &kgateway.GatewayExtension{} },
			func() *kgateway.GatewayExtensionList { return &kgateway.GatewayExtensionList{} },
			func(dst, src *kgateway.GatewayExtensionList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.GatewayExtensionList) []*kgateway.GatewayExtension {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.GatewayExtensionList, items []*kgateway.GatewayExtension) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
