// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeHTTPListenerPolicies implements HTTPListenerPolicyInterface
type fakeHTTPListenerPolicies struct {
	*gentype.FakeClientWithList[*kgateway.HTTPListenerPolicy, *kgateway.HTTPListenerPolicyList]
	Fake *FakeGatewayKgateway
}

func newFakeHTTPListenerPolicies(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.HTTPListenerPolicyInterface {
	return &fakeHTTPListenerPolicies{
		gentype.NewFakeClientWithList[*kgateway.HTTPListenerPolicy, *kgateway.HTTPListenerPolicyList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("httplistenerpolicies"),
			kgateway.SchemeGroupVersion.WithKind("HTTPListenerPolicy"),
			func() *kgateway.HTTPListenerPolicy { return &kgateway.HTTPListenerPolicy{} },
			func() *kgateway.HTTPListenerPolicyList { return &kgateway.HTTPListenerPolicyList{} },
			func(dst, src *kgateway.HTTPListenerPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.HTTPListenerPolicyList) []*kgateway.HTTPListenerPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.HTTPListenerPolicyList, items []*kgateway.HTTPListenerPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
