// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeListenerPolicies implements ListenerPolicyInterface
type fakeListenerPolicies struct {
	*gentype.FakeClientWithList[*kgateway.ListenerPolicy, *kgateway.ListenerPolicyList]
	Fake *FakeGatewayKgateway
}

func newFakeListenerPolicies(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.ListenerPolicyInterface {
	return &fakeListenerPolicies{
		gentype.NewFakeClientWithList[*kgateway.ListenerPolicy, *kgateway.ListenerPolicyList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("listenerpolicies"),
			kgateway.SchemeGroupVersion.WithKind("ListenerPolicy"),
			func() *kgateway.ListenerPolicy { return &kgateway.ListenerPolicy{} },
			func() *kgateway.ListenerPolicyList { return &kgateway.ListenerPolicyList{} },
			func(dst, src *kgateway.ListenerPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.ListenerPolicyList) []*kgateway.ListenerPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.ListenerPolicyList, items []*kgateway.ListenerPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
