// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackendConfigPolicies implements BackendConfigPolicyInterface
type fakeBackendConfigPolicies struct {
	*gentype.FakeClientWithList[*kgateway.BackendConfigPolicy, *kgateway.BackendConfigPolicyList]
	Fake *FakeGatewayKgateway
}

func newFakeBackendConfigPolicies(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.BackendConfigPolicyInterface {
	return &fakeBackendConfigPolicies{
		gentype.NewFakeClientWithList[*kgateway.BackendConfigPolicy, *kgateway.BackendConfigPolicyList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("backendconfigpolicies"),
			kgateway.SchemeGroupVersion.WithKind("BackendConfigPolicy"),
			func() *kgateway.BackendConfigPolicy { return &kgateway.BackendConfigPolicy{} },
			func() *kgateway.BackendConfigPolicyList { return &kgateway.BackendConfigPolicyList{} },
			func(dst, src *kgateway.BackendConfigPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.BackendConfigPolicyList) []*kgateway.BackendConfigPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *kgateway.BackendConfigPolicyList, items []*kgateway.BackendConfigPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
