// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	v1alpha1kgateway "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/v1alpha1/kgateway"
	gentype "k8s.io/client-go/gentype"
)

// fakeBackends implements BackendInterface
type fakeBackends struct {
	*gentype.FakeClientWithList[*kgateway.Backend, *kgateway.BackendList]
	Fake *FakeGatewayKgateway
}

func newFakeBackends(fake *FakeGatewayKgateway, namespace string) v1alpha1kgateway.BackendInterface {
	return &fakeBackends{
		gentype.NewFakeClientWithList[*kgateway.Backend, *kgateway.BackendList](
			fake.Fake,
			namespace,
			kgateway.SchemeGroupVersion.WithResource("backends"),
			kgateway.SchemeGroupVersion.WithKind("Backend"),
			func() *kgateway.Backend { return &kgateway.Backend{} },
			func() *kgateway.BackendList { return &kgateway.BackendList{} },
			func(dst, src *kgateway.BackendList) { dst.ListMeta = src.ListMeta },
			func(list *kgateway.BackendList) []*kgateway.Backend { return gentype.ToPointerSlice(list.Items) },
			func(list *kgateway.BackendList, items []*kgateway.Backend) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
