apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-tcp-gateway
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: tcp
    protocol: TCP
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-svc
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: test
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-tcp-route
spec:
  parentRefs:
  - name: example-tcp-gateway
  rules:
  - backendRefs:
    - name: tcp-svc
      port: 8000
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: proxy-protocol
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: example-tcp-gateway
  proxyProtocol: {}
