apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: default
spec:
  gatewayClassName: kgateway
  tls:
    frontend:
      default:
        validation:
          mode: AllowValidOnly
          caCertificateRefs:
            - name: ca-cert
              kind: ConfigMap
              group: ""
              namespace: default
      perPort:
        - port: 7443
          tls:
            validation:
              caCertificateRefs:
                - name: ca-cert-missing
                  kind: ConfigMap
                  namespace: default
                  group: ""
        - port: 8443
          tls:
            validation:
              caCertificateRefs:
                - name: ca-cert-missing
                  kind: Service
                  namespace: default
                  group: ""
        - port: 9443
          tls:
            validation:
              caCertificateRefs:
                - name: ca-cert-missing
                  kind: ConfigMap
                  namespace: default
                  group: ""
                - name: ca-cert
                  kind: ConfigMap
                  group: ""
                  namespace: default
        - port: 10443
          tls:
            validation:
              mode: AllowValidOnly
              caCertificateRefs:
                - name: ca-cert-2
                  kind: ConfigMap
                  namespace: ca-cert-2
                  group: ""
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret
  - name: listener-bad-certref
    protocol: HTTPS
    port: 7443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret
  - name: listener-partially-valid
    protocol: HTTPS
    port: 8443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Service
  - name: http
    protocol: HTTP
    port: 80
  - name: listener-bad-certkind
    protocol: HTTPS
    port: 9443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret
  - name: listener-missing-refgrant
    protocol: HTTPS
    port: 10443
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - "example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - name: httpbin
        port: 8000
---
kind: Secret
apiVersion: v1
metadata:
  name: https
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVQVENDQWlXZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFiTVFvd0NBWURWUVFEREFFcU1RMHcKQ3dZRFZRUUtEQVJ5YjI5ME1CNFhEVEl6TVRFd09ERTJORFExTjFvWERUTXpNVEV3TlRFMk5EUTFOMW93SGpFSwpNQWdHQTFVRUF3d0JLakVRTUE0R0ExVUVDZ3dIWjJGMFpYZGhlVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTit0V2hoa3QvNVFQTUw4UGorZ1JScUM1blp5TG9Sem5iK3hPazdQTVozRndtYUcKNThvbVhPRm16ZmJlK0VaaGE0UlBhK1BpdFhFbitjZkM5allYRU42dGM1WExWUjlKK1dCRXRhSUpoZlh2VzAvbgpraEg0MWFZa2NCQVMyTEh1U3l4WWd3VERMRzI1OUxVdVJFT3VGSVhtWUZJaGVlZTZ6V3dRMXk0Ujk1VzRoVGFzCi9JVk9wYmttbSsyM0ZVQ1Q3RTcvNzN0RFh3Q1dpekc3UnUyZ1p2aS9tK0ZRVUJCZmFPTGxzelQvVHNwNTB3YmUKY0hxY29UbWJNWUJpWDk1RFBYTWtnZ2g5M1R2bnBWb0taYVZhWDNOdHlGRGJOZnEyLzZaT2daNFlNZVgzb0VMUgpiVllpY01rU3lZRHJWbW9jeHZBMWdQQUsxd2NkVE1OcjlnY0F1b0VDQXdFQUFhT0JpRENCaFRBSkJnTlZIUk1FCkFqQUFNQXNHQTFVZER3UUVBd0lGNERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFnWUlLd1lCQlFVSEF3RXcKREFZRFZSMFJCQVV3QTRJQktqQWRCZ05WSFE0RUZnUVVxaW40SEhXN08wR3NLbGgwUEJ2SFFZSzRQT013SHdZRApWUjBqQkJnd0ZvQVVZb3l3TXpJN1BpWGtJd3FMSTdkNzA5SmJnVmN3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCCkFCQ3p2NUUrb3hYT3RBUi9UWWE2YWJMVm94WENPWFZVeVFRell5VFJoekJOY0Vjbk1NeDBHc2V1NHRXeUlmem8KNmQ5LzRkOWdmdDlRNnVTS1RZUkhYU0VIQUFsMmlEWGdQTTZoSk0vNmpxQlE2N1ErVkVrUTJWVUMySDZEYjF1Qwo2VGdldk9MdlA1eDhrS2FjZVNnYTdmSHZJcW95OHVmbm1BSzlhd2ZobE9hajBjUWcxQXV6aW14blhzTVQvdkNVCm9Xa2xPZSt0TDA2OEd3LytIMFJQMTJ6N2t6VGJDbXZuRWU4bk1QSXNrU21NZTcvUnZLcUFuYTd0NHFDOVdyRXgKWlFZK0NlOVhrTnI3RGJaZnprTmpqUFV2OEozdHN2dzY5Zm1HcVBEWVpHMm1HQjRzeGFyNy9mZG4rbGd3MDVsRwpBbEhhaWpXTlVGTWtmcXgvUzZnampEL0NPZVpRcVltM1hLY3RCWkFSUjNJRUR0RWNEUkRzNllvczhCUTBzbS9ECkhnNG1XWWR4Y283WlpnUzF6ZWlhdkNwRWxDaXEzWnB5c0EvS1NLS056Y1RIRk5acXBxYWFNdVQvaTBuaUI1MmEKZmpFSDUzdk1wYXhUK1IvcFIxQ1NMREZ6VDI3OTFMaEprZkJWVWwzQkdnOVY2VCt6bkl1Nkk1aVU1RlZZbVl3UApubS9EYitncE9JalEyU0w5Wm1nVkNvdjFvNTBTU3ZLN1RYSFVIaXFoZXlucDAyR1ZYYXpFT295ODBWcG04dW9JCklvS2NFOS9IUldOT0F5Uk41cWtYRDBnalpJOWM1aUtjV25kQ1B1cnBFZENNZUdiems1cWRUNGhZSFFsM2RKeW8KNHJoZm9MN051R1VUa0o1ZCtGdFBwaXRISkNEVGdUb05LTVNGcTcxbzRoMXkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktVd2dnU2hBZ0VBQW9JQkFRRGZyVm9ZWkxmK1VEekMKL0Q0L29FVWFndVoyY2k2RWM1Mi9zVHBPenpHZHhjSm1odWZLSmx6aFpzMzIzdmhHWVd1RVQydmo0clZ4Si9uSAp3dlkyRnhEZXJYT1Z5MVVmU2ZsZ1JMV2lDWVgxNzF0UDU1SVIrTldtSkhBUUV0aXg3a3NzV0lNRXd5eHR1ZlMxCkxrUkRyaFNGNW1CU0lYbm51czFzRU5jdUVmZVZ1SVUyclB5RlRxVzVKcHZ0dHhWQWsreE8vKzk3UTE4QWxvc3gKdTBidG9HYjR2NXZoVUZBUVgyamk1Yk0wLzA3S2VkTUczbkI2bktFNW16R0FZbC9lUXoxekpJSUlmZDA3NTZWYQpDbVdsV2w5emJjaFEyelg2dHYrbVRvR2VHREhsOTZCQzBXMVdJbkRKRXNtQTYxWnFITWJ3TllEd0N0Y0hIVXpECmEvWUhBTHFCQWdNQkFBRUNnZjhQVjFhUUwxaEVteTl0amc1WkR0SFFxRGFJZGZ0UUhwVmdCY0ZtMVVyZzBnSzAKWjZHa204V0REZ2ZqYlNlTlZ1RXhlRnFqV2RwWDkyeFhHbGNJdUV4SFgvZStsTXNRdnBWUllMcGhQblRuQU1YVgp0MG9rN1NYTFBVRll4OC8vcUcvWkZHTzA0UHJYNmFMRFNuZ0NBYXhxOFpNbFpFUkMyaUJKaTAwVXhGNHNKR25WCklJeHFLeVRnbWpBcFV6c1BDWXF5ci9aNmJTRkVnbVNxNzJobmt2Rm1PV3NYcldzRlZLY05iUUplWTRMMEJuWUsKWk5xODNmemt6ekpxbVh3OEVncWFPNlhWMmJtVmYrM1hSL3ViMDRGeXRya0Y5bE1JU0pWOUhkQmtRaGV2VzZhVApoSG5pblV6VkgyUlh4M1piYWw3ck1ZL0lOMWNmaFVlWm9BZDQ0ZGtDZ1lFQTh1bHorbXpPWXg0QVNnWUo0eVNICkdmc1VQeXpJUU9vaEVJQmtxMWNrUHJlbVhsdEdoWTcrRmtYYmh5cnVuOTRIREJJZWR0RWt0YjlZSDkvT0xNME8KK056TlhTYnlaQ3ZTa1U1ZlNNeUpDc3E3L01JTlVpNUxGN1FLQVF1ZXk3WDgvUGU3NHhFQ29hN1AvSlJkTnYrdgpjUnkyUEZOSlNGbTJGdkxGeDA4TDFWa0NnWUVBNjdxV3Q5dENpQ24zRXVPM2hEeFptZ3VSWU55Tk9TWkowdjR5Cm9zaXZ0WFl2ZGVYWGxGZWFWSEJtZG5vZUYrVTZ6TXpUQUY0d09jNmZpenpCMjlGVkxjWjJmTE5tWXc0RmxENFEKR0wzMHVJckQ5WXJraGZWZm85TW9aVHo2cWJnc0xQQnNZTXljelpFOThyb3dmZVp2MkUzQ1lRaDhOL1lGbXRmOQptWTViNFdrQ2dZQkQyc2pHQkl6bWpTUGhpYXhMWWhISFJTYlR1dXU1am0xc0VhR05aMHM5cGNsNGhDREFBRUNqCjhpR3ZzV04xRHUyREJyQ3gyaHhhRkxoR054dDkwazVEWUZLUm1lYU42dHZvTVM5V3c2UG9ldGRtZE1LSjJWcXEKcFdWQ0EzLzVRYjRJNEI4QS8raHZSOGpic29vVGFmc1ZLc01ST09hNHFpNitYRlM1SnpDVUNRS0JnRmZLN2tjYgpTZlFjYlFDRC90MG8vTlg2YVBLQ01iYVBJLytJM0tMenl6engvMHNSaHZDZ2o4SFMrdFkxTlBBQlY1emV5OWJmClBXYktKWEZkOTNVK3lWSjdEN1h4dXJnNWlLcGxVdWxrRmJpRk5lWkZERWMzMDU3WURidG1zcFJ6RzBEQmFodkQKR01NV3pOT1J0RzJ2WFFoYUxZS2wvbDE1S3kwNE5DTDBlaFBCQW9HQkFMK2RmaVFmUjhYVGMwMzF6R0xwQm1kdQpOMU81aDM1cUdIT0s4M25MY1VQSnhzc0JTSGVxNTZEVHBic3VMRjY0V1c2bk5KSWRwckdRLzNpOFZldzhDa05ZCmtXY2ZGWkdUTGM4b2g4Tkw4bWpiZGtITCs3M3ZuVy9FbEZRRDlWZTE3WWN0cEZKbUcwcVBSaFVWQzhkSG5RYnAKWXRMTTQxb01qQlQ3NUdjRjBZZ2wKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-cert
  namespace: default
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKzCCAhOgAwIBAgIUUe9RAlK3aQm6uAwK6EvlHIeRSTIwDQYJKoZIhvcNAQEL
    BQAwJTEQMA4GA1UEAwwHVGVzdCBDQTERMA8GA1UECgwIVGVzdCBPcmcwHhcNMjUx
    MjAzMTkyMDAwWhcNMjYxMjAzMTkyMDAwWjAlMRAwDgYDVQQDDAdUZXN0IENBMREw
    DwYDVQQKDAhUZXN0IE9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ALKdLcHlW1pqctfu2PVNuuUSfX18QfnKsPZk6WHlpRpzPiudT90sleHYt/mIWzk2
    +7Dx3DrjCnNj8bULkrYARp6c6dO5r4k8BBuzxE0we7RPoRVkBzIGkzK22Z2yz/cs
    LIOqKgSVXbneqYyJBlVYaJYPZ3uJH1QTcG9bOslckNVYPDtZuD0PGG8JzieNITSY
    smm5px68p/EVIr3OP5ecUMhCcEgWIo+992h5teIlOMpXpZb2Wm1ABpr8jaGJVgtO
    vn67mzRc7PBl5iT6cdUnG99LUMIhj73cKy1W+9i3elF8w4SEW/7uMvNK0WwkFaFl
    l8Hzi8yfsV3EC0WPRuqp3jcCAwEAAaNTMFEwHQYDVR0OBBYEFNZroy3SiFR+l3HI
    tw+npPPl5M5mMB8GA1UdIwQYMBaAFNZroy3SiFR+l3HItw+npPPl5M5mMA8GA1Ud
    EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIpnex0iW9jtbYJhfxzE4Wmm
    fNG3n13wZae/brOnj69VkK6ZJ35Ogjv9eybJIaicYCpkQhaiA5X7BU6cAc90IWdv
    b7tury8qT1zwbTxzxeGpvct6877OtcClk1BNb9OqdBdZncDg+WeS9ZkQm/aqEapA
    QuJci70Ynkre0udQtenazF8njlvngaw3GJdQ6ogZ1m5W0PPVaAMC/Ie88eolH0x8
    EHk+WI7OPFRYrj7mgl/n3ZSE/GT3Er/iz6KSBRiR3MO8oX0EpBIoAoliqzN3cmYX
    YViYxaXeR0p3dIhgHI9toNXc0At575ZPmjJchLdWzkjPdThy7VYKaK6yxicYVLI=
    -----END CERTIFICATE-----
apiVersion: v1
kind: Namespace
metadata:
  name: ca-cert-2
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-cert-2
  namespace: ca-cert-2
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKzCCAhOgAwIBAgIUUe9RAlK3aQm6uAwK6EvlHIeRSTIwDQYJKoZIhvcNAQEL
    BQAwJTEQMA4GA1UEAwwHVGVzdCBDQTERMA8GA1UECgwIVGVzdCBPcmcwHhcNMjUx
    MjAzMTkyMDAwWhcNMjYxMjAzMTkyMDAwWjAlMRAwDgYDVQQDDAdUZXN0IENBMREw
    DwYDVQQKDAhUZXN0IE9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    ALKdLcHlW1pqctfu2PVNuuUSfX18QfnKsPZk6WHlpRpzPiudT90sleHYt/mIWzk2
    +7Dx3DrjCnNj8bULkrYARp6c6dO5r4k8BBuzxE0we7RPoRVkBzIGkzK22Z2yz/cs
    LIOqKgSVXbneqYyJBlVYaJYPZ3uJH1QTcG9bOslckNVYPDtZuD0PGG8JzieNITSY
    smm5px68p/EVIr3OP5ecUMhCcEgWIo+992h5teIlOMpXpZb2Wm1ABpr8jaGJVgtO
    vn67mzRc7PBl5iT6cdUnG99LUMIhj73cKy1W+9i3elF8w4SEW/7uMvNK0WwkFaFl
    l8Hzi8yfsV3EC0WPRuqp3jcCAwEAAaNTMFEwHQYDVR0OBBYEFNZroy3SiFR+l3HI
    tw+npPPl5M5mMB8GA1UdIwQYMBaAFNZroy3SiFR+l3HItw+npPPl5M5mMA8GA1Ud
    EwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIpnex0iW9jtbYJhfxzE4Wmm
    fNG3n13wZae/brOnj69VkK6ZJ35Ogjv9eybJIaicYCpkQhaiA5X7BU6cAc90IWdv
    b7tury8qT1zwbTxzxeGpvct6877OtcClk1BNb9OqdBdZncDg+WeS9ZkQm/aqEapA
    QuJci70Ynkre0udQtenazF8njlvngaw3GJdQ6ogZ1m5W0PPVaAMC/Ie88eolH0x8
    EHk+WI7OPFRYrj7mgl/n3ZSE/GT3Er/iz6KSBRiR3MO8oX0EpBIoAoliqzN3cmYX
    YViYxaXeR0p3dIhgHI9toNXc0At575ZPmjJchLdWzkjPdThy7VYKaK6yxicYVLI=
    -----END CERTIFICATE-----
---